% !TeX encoding = UTF-8
% !TeX spellcheck = fr-classique
<<Notions-parent, echo=FALSE, cache=FALSE>>=
set_parent('Mesures_de_la_Biodiversite.Rnw')
opts_chunk$set(cache=TRUE, warning=FALSE, tidy=TRUE, fig.width=8, fig.height=6, out.width='.8\\maxwidth', tidy.opts=list(blank=FALSE, width.cutoff=60), size="scriptsize")
options(width=60)
# Graphiques postscript
setEPS(horizontal=FALSE, onefile=FALSE, paper="special", family="ComputerModern", encoding="TeXtext.enc", width=8.0, height=6.0)
par(mar=c(0,0,0,0))
@

\LargeMargins
\selectlanguage{french}
\sisetup{locale = FR}
\chapter{Notions de Diversité}

\lettrine{L}{e terme} \foreignlanguage{english}{\emph{biodiversity}} est attribué \autocite{Meine2006} à Walter Rosen, un membre du \emph{National Research Council} américain, qui a commencé à contracter les termes \foreignlanguage{english}{\emph{biological diversity}} pendant la préparation d'un colloque dont les actes seront publiés sous le titre \foreignlanguage{english}{\og Biodiversity\fg{}} \autocite{Wilson1988}.
La question de la diversité biologique intéressait les écologues bien avant l'invention de la biodiversité, mais le néologisme a connu un succès fulgurant \autocite{Blandin2014} en même temps qu'il devenait une notion floue, dans lequel chacun peut placer ce qu'il souhaite y trouver, au point de lui retirer son caractère scientifique \autocite{Delord2014}. 
Une cause de ce glissement est que la biodiversité a été nommée pour attirer l'attention sur son érosion, en lien avec la biologie de la conservation. 
Cette érosion concernant potentiellement de nombreux aspects du monde vivant, la définition de la biodiversité fluctue selon les besoins: \textcite{DeLong1996} en recense 85 dans les dix premières années de littérature. 
Les indicateurs de la biodiversité peuvent englober bien d'autres choses que la diversité du vivant : le nombre d'espèces menacées (par exemple la liste rouge de l'IUCN), la taille des populations ou la surface des écosystèmes préservés, la dégradation des habitats, la menace pesant sur des espèces emblématiques...
Une mesure rigoureuse et cohérente de la diversité peut pourtant être construite pour clarifier beaucoup (mais pas tous) des concepts qui constituent la biodiversité. 

Dans l'introduction du premier chapitre des actes de ce qui était devenu le \og Forum sur la Biodiversité\fg{}, Wilson utilise le mot dans le sens étroit de nombres d'espèces. 
L'élargissement de la notion aux \og systèmes naturels\fg{} et à l'opposé à la diversité génétique intraspécifique est venu du monde de la conservation \autocite{Speth1992}.
La déclaration de Michel Loreau, président du du comité scientifique de la conférence de Paris en 2005 \autocite{Loreau2005} en donne une définition aboutie:
\begin{quotation}
  ``La Terre abrite une extraordinaire diversité biologique, qui inclut non seulement les espèces qui habitent notre planète, mais aussi la diversité de leurs gènes, la multitude des interactions écologiques entre elles et avec leur environnement physique, et la variété des écosystèmes complexes qu'elles constituent. Cette biodiversité, qui est le produit de plus de 3 milliards d'années d'évolution, constitue un patrimoine naturel et une ressource vitale dont l'humanité dépend de multiples façons.''
\end{quotation}

Aujourd'hui encore, le terme \emph{biodiversité} concerne le plus souvent la richesse en espèces d'un écosystème. 
Pour simplifier la présentation, le niveau d'étude dans ce document sera en général celui des espèces (autre concept flou\autocite{Hey2001}).
La prise en compte de la totalité des êtres vivants est généralement hors de portée.
La mesure de diversité est alors limitée à un taxocène, c'est-à-dire un sous-ensemble des espèces d'une communauté reliées taxonomiquement: les papillons, les mammifères, les arbres (la délimitation du sous-ensemble n'est pas forcément strictement taxonomique)...

Un objet privilégié des études sur la biodiversité est, depuis le Forum, la forêt tropicale parce qu'elle est très diverse et un enjeu pour la conservation. 
La plupart des exemples concerneront ici les arbres de la forêt tropicale, qui ont l'avantage d'être clairement définis en tant qu'individus (donc simples à compter) et posent des problèmes méthodologiques considérables pour l'estimation de leur diversité à partir de données réelles.


On peut bien évidemment s'intéresser à d'autres niveaux et d'autres objets, par exemple la diversité génétique (en termes d'allèles différents pour certains gènes ou marqueurs) à l'intérieur d'une population. 
On gardera toujours à l'esprit que la prise en compte de la diversité spécifique n'est pas la seule approche, les méthodes présentées ici s'appliquent à la mesure de la diversité en général, pas même nécessairement biologique.

L'objectif de ce document est de traiter la mesure de la biodiversité, pas son importance en tant que telle 
(on se référera par exemple à \textcite{Chapin2000} pour une revue sur cette question ou \textcite{Cardinale2012} pour les conséquences de l'érosion de la biodiversité sur les services écosystémiques). 
La mesure de la diversité est un sujet important en tant que tel \autocite{Purvis2000}, pour permettre de formaliser les concepts et de les appliquer à la réalité. 
La question est loin d'être épuisée, et fait toujours l'objet d'une recherche active et de controverses \autocite{Ricotta2005b}.

\section{Composantes}

\figureSC{Composantes}
{
  Importance de la richesse (en haut) et de l'équitabilité (en bas) pour la définition de la diversité. 
  Ligne du haut: toutes choses égales par ailleurs, une communauté de 7 espèces semble plus diverse qu'une communauté de 2 espèces. 
  Ligne du bas: à richesse égale, une communauté moins équitable (à gauche) semble moins diverse. 
  Colonne de gauche: une communauté moins riche (en haut) peut sembler plus diverse si elle est plus équitable. 
  Colonne de droite: \emph{idem} pour la communauté du bas.
}
{
  \includegraphics[width=.5\maxwidth]{Composantes}
}

Une communauté comprenant beaucoup d'espèces mais avec une espèce dominante n'est pas perçue intuitivement comme plus diverse qu'une communauté avec moins d'espèces, mais dont les effectifs sont proches (Figure~\ref{Composantes}, colonne de gauche). 
La prise en compte de deux composantes de la diversité, appelées richesse et équitabilité, est nécessaire \autocite{Whittaker1965}.


\subsection{Richesse}

La richesse (terme introduit par \textcite{Mcintosh1967}) est le nombre (ou une fonction croissante du nombre) de classes différentes présentes dans le système étudié, par exemple le nombre d'espèces d'arbres dans une forêt.

Un certain nombre d'hypothèses sont assumées plus ou moins explicitement:

\begin{itemize}
  \item  Les classes sont bien connues: compter le nombre d'espèces a peu de sens si la taxonomie n'est pas bien établie. 
  C'est parfois une difficulté majeure quand on travaille sur les microorganismes;
  \item  Les classes sont équidistantes: la richesse augmente d'une unité quand on rajoute une espèce, que cette espèce soit proche des précédentes ou extrêmement originale.
\end{itemize}

L'indice de richesse le plus simple et le plus utilisé est tout simplement le nombre d'espèces $S$.


\subsection{\'Equitabilité}

La régularité de la distribution des espèces (équitabilité en Français, \foreignlanguage{english}{\emph{evenness}} ou \foreignlanguage{english}{\emph{equitability}} en anglais) est un élément important de la diversité. 
Une espèce représentée abondamment ou par un seul individu n'apporte pas la même contribution à l'écosystème. 
Sur la figure~\ref{Composantes}, la ligne du bas présente deux communautés de 4 espèces, mais celle de droite est beaucoup plus équitable de celle de gauche et semble intuitivement plus diverse.
\`A nombre d'espèces égal, la présence d'espèces très dominantes entraîne mathématiquement la rareté de certaines autres: on comprend donc assez intuitivement que le maximum de diversité sera atteint quand les espèces auront une répartition très régulière.

Un indice d'équitabilité est indépendant du nombre d'espèces (donc de la richesse).

La plupart des indices courants, comme ceux de Simpson ou de Shannon, évaluent à la fois la richesse et l'équitabilité.


\subsection{Disparité}

Les mesures classiques de la diversité, dites mesures de diversité neutre (\foreignlanguage{english}{\emph{species-neutral diversity}}) ou taxonomique ne prennent pas en compte une quelconque distance entre classes. 
Pourtant, deux espèces du même genre sont de toute évidence plus proches que deux espèces de familles différentes. 
Les mesures de diversité phylogénétique et de diversité fonctionnelle prennent en compte cette notion, qui nécessite quelques définitions supplémentaires \autocite{Mouillot2005, Ricotta2007}.

La mesure de la différence entre deux classes est souvent une distance, mais parfois une mesure qui n'a pas toutes les propriétés d'une distance: une dissimilarité.
Les mesures de \emph{divergence} \autocite{Pavoine2011} sont construites à partir de la dissimilarité entre les classes, avec ou sans pondération par la fréquence.

La disparité \autocite{Runnegar1987}, divergence moyenne entre deux espèces (indépendamment des fréquences), ou de façon équivalente la longueur totale des branches d'un arbre phylogénétique, est la composante qui décrit à quel point les espèces sont différentes les unes des autres.

Les mesures de \emph{régularité} décrivent la façon dont les espèces occupent l'espace des niches (régularité fonctionnelle) ou la régularité dans le temps et entre les clades des évènements de spéciation représentés par un arbre phylogénétique.
Ce concept complète celui d'équitabilité dans les mesures classiques: la diversité augmente avec la richesse, la divergence entre espèces, et la régularité (qui se réduit à l'équitabilité quand toutes les espèces sont également divergentes entre elles).


\subsection{Agrégation}

\`A partir d'une large revue de la littérature dans plusieurs disciplines scientifiques s'intéressant à la diversité (au-delà de la biodiversité), \textcite{Stirling2007} estime que les trois composantes, qu'il nomme \emph{variété} (richesse), \emph{équilibre} (équitabilité) et \emph{disparité}, recouvrent tous les aspects de la diversité.

Stirling  définit la propriété d'\emph{agrégation} comme la capacité d'une mesure de diversité à combiner explicitement les trois composantes précédentes.
Cela ne signifie pas que les composantes contribuent indépendamment les unes des autres à la diversité \autocite{Jost2010}.



\section{Niveaux de l'étude}

La diversité est classiquement estimée à plusieurs niveaux emboîtés, nommés $\alpha$, $\beta$ et $\gamma$ par \textcite[][page 320]{Whittaker1960}, qui a nommé $\alpha$ la diversité locale qu'il mesurait avec l'indice $\alpha$ de Fisher (voir page~\pageref{eq:AlphaFisher}) et a utilisé les lettres suivantes selon ses besoins.

\subsection[Diversité alpha, beta et gamma]{Diversité $\alpha$, $\beta$ et $\gamma$}

La diversité $\alpha$ est la diversité locale, mesurée à l'intérieur d'un système délimité. 
Plus précisément, il s'agit de la diversité dans un habitat uniforme de taille fixe.

\figureSC{Gaston2000}
{Patrons de biodiversité \autocite[][figure 1]{Gaston2000}. 
  (a) Le nombre d'espèces de vers de terre augmente en fonction de la surface échantillonnée, de \SI{100}{\meter\squared} à plus de \SI{500000}{\kilo\meter\squared} selon la relation d'Arrhenius (voir page~\pageref{sec:Arrhenius}). 
  (b) Nombre d'espèces d'oiseaux en fonction de la latitude. 
  (c) Relation entre la richesse régionale et la richesse locale. 
  (d) Nombre d'espèces de chauves-souris en fonction de l'altitude dans une réserve au Pérou. 
  (e) Nombre d'espèces de végétaux ligneux en fonction des précipitations en Afrique du Sud}
{\includegraphics[width=\maxwidth]{Gaston2000}}

De façon générale \autocite{Gaston2000}, la richesse spécifique diminue avec la latitude (la diversité est plus grande dans les zones tropicales, et au sein de celles-ci, quand on se rapproche de l'équateur), voir figure~\ref{Gaston2000}.
La tendance est la même pour la diversité génétique intraspécifique \autocite{Miraldo2016}.
La richesse diminue avec l'altitude. 
Elle est généralement plus faible sur les îles, où elle décroît avec la distance au continent, source de migrations.

La diversité $\beta$ mesure à quel point les systèmes locaux sont différents. Cette définition assez vague fait toujours l'objet de débats \autocite{Moreno2010}.

Enfin, la diversité $\gamma$ est similaire à la diversité $\alpha$, prise en compte sur l'ensemble du système étudié. 
Les diversités $\alpha$ et $\gamma$ se mesurent donc de la même façon.


\subsection{Décomposition}

\textcite{Whittaker1977} a proposé sans succès une normalisation des échelles d'évaluation de la biodiversité, en introduisant la diversité régionale $\varepsilon$ ($\gamma$ étant réservé au paysage et $\alpha$ à l'habitat) et la diversité $\delta $ entre les paysages. 
Seuls les trois niveaux originaux ont été conservés par la littérature, sans définition stricte des échelles d'observation.

La distinction entre les diversités $\alpha$ et $\beta$ dépend de la finesse de la définition de l'habitat. 
La distinction de nombreux habitats diminue la diversité $\alpha$ au profit de la $\beta$. 
Il est donc important de définir une mesure qui ne dépende pas de ce découpage, donc une mesure cumulative (additive ou multiplicative) décrivant la diversité totale, décomposable en la somme ou le produit convenablement pondérés de toutes les diversités $\alpha$ des habitats (diversité intra) et de la diversité $\beta$ inter-habitat.

Nous appellerons \emph{communauté} le niveau de découpage concernant la diversité $\alpha$ et \emph{méta-communauté} le niveau de regroupement pour l'estimation de la diversité $\gamma$.


\section{Le problème de l'espèce}

\'Evaluer la richesse spécifique suppose que les espèces soient définies clairement, ce qui n'est de toute évidence pas le cas \autocite{Casetta2014a}. 
Le premier aspect du problème concerne la nature des espèces: réalité naturelle ou seulement représentation simplificatrice. 
Une analyse historique et philosophique en est faite par \textcite{Richards2010}. 
L'autre aspect, avec des conséquences pratiques plus immédiates, concerne leur délimitation. 
\textcite{Mayden1997} recense 22 définitions différentes du concept d'espèce.

Le concept le plus répandu est celui d'espèce \emph{biologique} \autocite{Mayr1942, Dobzhansky1937} : un \og groupe de populations naturelles isolées reproductivement les unes des autres\fg{} \autocite{Mayr1970}. 
Lorsque les populations d'une espèce sont isolées géographiquement, leur capacité à se reproduire ensemble est toute théorique (et d'ailleurs rarement vérifiée expérimentalement). 
Des populations allopatriques n'ont pas de flux de gènes réels entre elles et peuvent être considérées comme des espèces distinctes selon le concept d'espèce \emph{phylogénétique} : \og le plus petit groupe identifiable d'individus avec un pattern commun d'ancêtres et de descendants\fg{} \autocite{Cracraft1983}.
C'est l'unité génétique détectée par la méthode du coalescent pour la délimitation des espèces \autocite{Sukumaran2017}.
Le nombre d'espèces phylogénétiques est bien supérieur au nombre d'espèces biologiques. 
Enfin, \textcite{VanValen1976} définit les espèces par la niche écologique qu'elles occupent (à partir de l'exemple des chênes blancs européens) plutôt que par les flux de gènes (permanents entre les espèces distinctes): le concept \emph{écologique} d'espèce est proche de celui de complexe d'espèces (ensemble d'espèces voisines échangeant des gènes \autocite{Pernes1984}).

Le choix de la définition modifie considérablement sur la quantification de la richesse \autocite{Agapow2004}. 
Des problèmes méthodologiques s'ajoutent aux problèmes conceptuels \autocite{Hey2001} : la séparation ou le regroupement de plusieurs populations ou morphotypes en un nombre plus ou moins grand d'espèces est un choix qui reflète les connaissances du moment et peut évoluer \autocite{Barberousse2014}.

L'impact du problème de l'espèce sur la mesure de la diversité reste sans solution à ce stade, si ce n'est d'utiliser les mêmes définitions si des communautés différentes doivent être comparées. 
L'approche phylogénétique (page~\pageref{chap:Phyloentropie}) règle le problème : si deux taxons très semblables apportent à peine plus de diversité qu'un seul taxon, le choix de les distinguer ou non n'est pas critique.



\chapter{Outils}

\begin{Essentiel}
  La diversité peut être décrite localement par une courbe d'accumulation (SAC) qui représente le nombre d'espèces échantillonnées en fonction de l'effort.
  \`A une échelle plus large, cette courbe s'appelle relation aire-espèces (SAR).
  
  La distribution des abondances des espèces (SAD) est représentée par une histogramme des fréquences ou un diagramme rang-abondance.
  
  Le taux de couverture est la somme des probabilités des espèces observées étant donné l'effort d'échantillonnage. Il peut être estimé précisément à partir des données d'inventaire. Le taux de complétude est la proportion (en nombre) des espèces observées.
\end{Essentiel}

\lettrine{Q}{uelques} outils sont nécessaires avant d'entrer dans le c\oe ur du sujet. Les relations décrivant le nombre d'espèces en fonction de la taille de l'échantillon (relations aire-espèces) et la distribution de l'abondance des espèces sont importants pour les écologues. La mesure de l'exhaustivité de l'échantillonnage par le taux de couverture sera la base de l'estimation de la diversité à partir de données réelles.



\section{Calculs et données}

La présentation des mesures de diversité est donnée avec un usage intensif du formalisme mathématique.
La liste des notations est fournie en préambule du document, on s'y référera autant que nécessaire.

Les calculs sont réalisés dans R \autocite{R}, essentiellement avec le package \emph{entropart} \autocite{Marcon2014c}. 
L'ensemble du code est disponible sur le site web\footnote{\url{http://www.ecofog.gf/spip.php?article427}} où se trouvent les mises à jour de ce document.

Les données sont souvent celles de la parcelle forestière permanente de Barro Colorado Island (BCI)\autocite{Condit2012}: \SI{50}{\hectare} de forêt tropicale dont les arbres de plus de \SI{1}{\centi\meter} de diamètre à hauteur de poitrine (DBH: \foreignlanguage{english}{\emph{Diameter at Breast Height}}) ont été inventoriés.
Le jeu de données utilisé pour les exemples est une version réduite aux arbres de plus de \SI{10}{\centi\meter} disponible dans le package \emph{vegan} \autocite{Oksanen2012}.
D'autres exemples utilisent des inventaires de la forêt de Paracou en Guyane française \autocite{Gourlet-Fleury2004}, principalement deux placettes d'un hectare numérotées 6 et 18, dont les données, toujours des arbres de plus de \SI{10}{\centi\meter} DBH, se trouvent dans le package \emph{entropart}.



\section{SAD et SAR}

\figureSC[t]{SARFig}
{Courbe d'accumulation des espèces d'arbres du dispositif de Barro Colorado Island. 
  Le nombre d'espèces est cumulé dans l'ordre des carrés d'un hectare du dispositif.}
{
  <<SARFig, echo=FALSE, results='hide', message=FALSE>>=
  <<SARCode>>
  @
}

La courbe aire-espèces (SAR: \foreignlanguage{english}{\emph{Species Area Relationship}}) représente le nombre d'espèces observées en fonction de la surface échantillonnée (Figure~\ref{Williamson2001}, page~\pageref{Williamson2001}).
Il existe plusieurs façons de prendre en compte cette relation \autocite{Scheiner2003}, classables en deux grandes familles \autocite{Dengler2009} :
\begin{itemize}
  \item Dans une SAR au sens strict, chaque point représente une communauté. 
  La question traitée est la relation entre le nombre d'espèces et la taille de la communauté;
  \item Si les points représentent un effort d'échantillonnage différent dans même communauté, on parle de courbe d'accumulation (SAC: \foreignlanguage{english}{\emph{Species Acumulation Curve}}). Une courbe de raréfaction (\foreignlanguage{english}{\emph{Rarefaction Curve}}) peut être calculée en réduisant par des outils statistiques l'effort d'échantillonnage réel pour obtenir une SAC théorique, libérée des aléas de l'ordre de prise en compte des données.
\end{itemize}

La Figure~\ref{SARFig}
\verbfootnote{Le code R nécessaire pour réaliser la figure est:
  <<SARCode, eval=FALSE>>=
  library("vegan")
  data(BCI)
  Cumul <- apply(BCI, 2, cumsum)
  Richesse <- apply(Cumul, 1, function(x) sum(x>0))
  plot(y=c(0, Richesse), x=0:50, type="l", xlab="Surface (ha)")
  @
} montre l'accumulation des espèces pour les données de BCI.
Une SAC peut être tracée en fonction de la surface, du nombre d'individus ou du nombres de placettes d'échantillonnage, selon les besoins.


\figureSC{SADRACFig}
{Histogramme des fréquences (diagramme de Preston, en haut) des arbres du dispositif de Barro Colorado Island. 
  En abscisse: le nombre d'arbres de chaque espèce (en logarithme); en ordonnée: le nombre d'espèces).
  Diagramme rang-abondance (diagramme de Whittaker, en bas) correspondant. 
  Les points sont les données, la courbe est l'ajustement d'une distribution log-normale.}
{
  %  \begin{tabular}{cc}
  <<SADFig, echo=FALSE, results='hide', out.width='.7\\maxwidth'>>=
  <<SADCode>>
  @
  %  &
  <<RACFig, echo=FALSE, results='hide', out.width='.7\\maxwidth'>>=
  <<RACCode>>
  @
  %  \end{tabular}
}

La distribution de l'abondance des espèces (SAD: \foreignlanguage{english}{\emph{Species Abundance Distribution}}) est la loi qui donne l'abondance attendue de chaque espèce d'une communauté. 
Les espèces ne sont pas identifiées individuellement, mais par le nombre d'individus leur appartenant (Figure~\ref{SADRACFig}
\verbfootnote{Code R pour la figure:
  <<SADCode, eval=FALSE, tidy=FALSE>>=
  data(BCI)
  Ns <- sort(colSums(BCI), decr = TRUE)
  N <- sum(Ns)
  hist(log(Ns), main = NULL , xlab = expression(ln(N[s])), 
  ylab="Nb Espèces")
  @
  <<RACCode, eval=FALSE, tidy=FALSE>>=
  library("entropart")
  plot(as.AbdVector(Ns), Distribution = "lnorm")
  @
}). 
Elle peut être représentée sous la forme d'un histogramme des fréquences (diagramme de \textcite{Preston1948}, en haut) ou bien d'un diagramme rang-abondance (RAC: \foreignlanguage{english}{\emph{Rank Abundance Curve}} ou diagramme de \textcite{Whittaker1965}, en bas). 
Le RAC est souvent utilisé pour reconnaître des distributions connues. 
\textcite{Izsak2012} ont étudié les propriétés des RAC pour les principales SAD.

Les SAD ne sont pas traitées en détail ici: on se reportera à \textcite{Magurran1988}, \textcite{McGill2007} et Izsák et Pavoine. 
Les SAD nécessaires à la compréhension de la suite sont:

\begin{itemize}
  \item  La distribution géométrique \autocite{Motomura1932, Whittaker1972};
  \item  La distribution en log-séries de \textcite{Fisher1943};
  \item  La distribution log-normale \autocite{Preston1948};
  \item  Le modèle Broken Stick \autocite{MacArthur1957}.
\end{itemize}



\section{Taux de couverture}
\label{sec:Couverture}


\subsection{Formule des fréquences de Good-Turing}

La relation fondamentale entre les fréquences des espèces est due à Turing et a été publiée par \textcite{Good1953}.
En absence de toute information sur la loi de distribution des espèces, en supposant seulement que les individus sont tirés indépendamment les uns des autres selon une loi multinomiale respectant ces probabilités, la formule de Good-Turing relie la probabilité moyenne $\alpha_\nu$ d'une espèce représentée $\nu$ fois (c'est-à-dire par $\nu$ individus) au rapport entre les nombres d'espèces représentées $\nu+1$ fois et $\nu$ fois:

\begin{equation}
  \alpha_\nu \approx \frac{(\nu+1)}{n} \frac{\xq{s}{}{n}{\nu+1}{}}{\xq{s}{}{n}{\nu}{}}.
\end{equation}

Les singletons ($\xq{s}{}{n}{1}{}$: le nombre d'espèces observées une seule fois) et les doubletons ($\xq{s}{}{n}{2}{}$: le nombre d'espèces observées deux fois) ont une importance centrale.
Pour $\nu=1$, on a : $\alpha_1 = \nicefrac{2 \xq[\,]{s}{}{n}{2}{}}{\xq{s}{}{n}{1}{}}$: la fréquence d'une espèce typiquement représentée par un singleton est environ égale à deux fois le rapport entre le nombre des singletons et des doubletons.
Pour $\nu=0$, l'ignorance du nombre d'espèces non échantillonnées ${\xq{s}{}{n}{0}{}}$ pose problème mais le produit $\alpha_0 \times {\xq{s}{}{n}{0}{}} = \pi_0$, la probabilité totale des espèces non représentées, peut être estimée par $\nicefrac{{\xq{s}{}{n}{1}{}}}{n}$.
Ces relations sont le fondement des estimateurs de richesse de Chao présentées ci-dessous.

La relation a été précisée \autocite[][eq. 6 et 7a]{Chiu2014a} en limitant les approximations dans les calculs.
La seule nécessaire est que les probabilités des espèces représentées le même nombre de fois $\nu$ varient peu et puissent être considérées toutes égales à $\alpha_\nu$. Alors, $\alpha_\nu$ est estimé par
\begin{equation}
  \label{eq:GoodTuring2014}
  \hat{\alpha}_\nu = \frac{\left(\nu+1 \right) \xq{s}{}{n}{\nu+1}{}}{\left(n-\nu \right) \xq{s}{}{n}{\nu}{} + \left(\nu+1 \right) \xq{s}{}{n}{\nu+1}{}}.
\end{equation}

Ce nouvel estimateur est à la base de l'estimateur de Chao amélioré et des estimateurs d'entropie de Chao et Jost (pages~\pageref{sec:BiaisShannon} et \pageref{sec:BiaisHCDT}).

\subsection{Taux de couverture et déficit de couverture}
\label{sec:DefCouverture}

\textcite{Good1953} définit le taux de couverture (\foreignlanguage{english}{\emph{sample coverage}}) de l'échantillonnage comme la proportion des espèces découvertes,
$$C=\sum^S_{s=1}{{\mathbf 1}\left(n_s>0\right)p_s},$$
où ${\mathbf 1}(\cdot)$ est la fonction indicatrice. 
Son complément à 1 est appelé déficit de couverture (\foreignlanguage{english}{\emph{coverage deficit}}).

Le taux de couverture augmente avec l'effort d'échantillonnage. 
Plus il est élevé, meilleures seront les estimations de la diversité. 
Pour comparer deux communautés par des courbes de raréfaction, \textcite{Chao2012b} montrent que le taux de couverture plutôt que la taille de l'échantillon doit être identique. 
Les estimateurs de la diversité développés plus loin reposent largement sur cette notion pour la correction du biais d'échantillonnage \autocite{Dauby2012} (la sous-estimation systématique de la diversité due aux espèces non observées, un des éléments du biais d'estimation).

L'estimateur du taux de couverture, que Good attribue à Turing, est selon la relation des fréquences vues plus haut :

\begin{equation}
  \label{eq:CGood}
  \hat{C} = 1-\frac{\xq{s}{}{n}{1}{}}{n}.
\end{equation}

Cet estimateur est biaisé \autocite{Zhang2007}. En réalité,
\begin{equation}
  \label{eq:CsansBiais}
  C = 1-\frac{{\mathbb E}(\xq{S}{}{n}{1}{}) - \pi_1}{n}.
\end{equation}

L'estimateur de Good néglige le terme $\pi_1$, la somme des probabilités des espèces observées une fois. Ce terme peut être estimé avec un biais plus petit.
\textcite{Chao1988} puis \textcite{Zhang2007} proposent l'estimateur suivant, qui utilise toute l'information disponible et a le plus petit biais possible:

\begin{equation}
  \label{eq:CZhang}
  \hat{C}=1-\sum^{n}_{\nu=1}{\left(-1\right)}^{\nu+1}{\binom{n}{\nu}}^{-1}\xq[\,]{s}{}{n}{\nu}{}.
\end{equation}

Les termes de la somme décroissent très vite avec $\nu$.
En se limitant à $\nu=1$, l'estimateur se réduit à celui de Good.

\textcite{Esty1983}, complété par \textcite{Zhang2009}, a montré que l'estimateur était asymptotiquement normal et a calculé l'intervalle de confiance de $\hat{C}$:

\begin{equation}
  C=\hat{C}\pm t^{n}_{1-\alpha/2} \frac{\sqrt{\xq{s}{}{n}{1}{}\left(1-\frac{\xq{s}{}{n}{1}{}}{n}\right)+2\xq[\,]{s}{}{n}{2}{}}}{n}.
\end{equation}

Où $t^{n}_{1-\alpha/2}$ est le quantile d'une loi de Student à $n$ degrés de libertés au seuil de risque $\alpha$, classiquement 1,96 pour $n$ grand et $\alpha=5\%$.


Un autre estimateur est utilisé dans le logiciel SPADE \autocite{Chao2010a} et son portage sous R, le package \emph{spadeR} \autocite{Chao2016c}.
Il est la base des estimateurs d'entropie de Chao et Jost (page~\pageref{sec:BiaisHCDT}).
L'estimation de l'équation~(\ref{eq:CsansBiais}) donne la relation
\begin{equation}
  \hat{C} = 1-\frac{\xq{s}{}{n}{1}{} - \hat{\pi}_1}{n}.
\end{equation}

Or, $\hat{\pi}_1 = \xq{s}{}{n}{1}{} \hat{\alpha}_1$.
$\alpha_1$ peut être estimé par la relation de Good-Turing (\ref{eq:GoodTuring2014}), en remplaçant $\xq{s}{}{n}{0}{}$ par l'estimateur Chao1 (équation~\ref{eq:Chao1}).
Alors:

\begin{equation} 
  \label{eq:CChao}
  \hat{C} = 1-\frac{\xq{s}{}{n}{1}{}}{n}(1 - \hat{\alpha}_1)
  = 1-\frac{\xq{s}{}{n}{1}{}}{n}\left[\frac{\left(n-1\right)\xq[]{s}{}{n}{1}{}}{\left(n-1\right)\xq[]{s}{}{n}{1}{}+2\xq[\,]{s}{}{n}{2}{}}\right].
\end{equation}


Dans le package \emph{entropart}, la fonction \code{Coverage} calcule les trois estimateurs (celui de Zhang et Huang par défaut):

<<Coverage>>=
data(Paracou618)
Coverage(Paracou618.MC$Ns)
@


\textcite{Chao2012b} montrent que la pente de la courbe d'accumulation donnant l'espérance du nombre d'espèces en fonction du nombre d'individus (courbe de raréfaction de la Figure~\ref{Gotelli2001}) est égale au déficit de couverture,

\begin{equation}
  1-{\mathbb E}\left(\xq{C}{}{n}{}{}\right)={\mathbb E}\left(\xq{S}{}{n+1}{}{}\right)-{\mathbb E}\left(\xq{S}{}{n}{}{}\right),
\end{equation}

où $\xq{C}{}{n}{}{}$ est le taux de couverture d'un échantillon de taille $n$ et $\xq{{S}}{}{n}{}{}$ le nombre d'espèces découvertes dans cet échantillon.


Les estimateurs présentés ici supposent une population de taille infinie (de façon équivalente, les individus sont tirés avec remise).
Le cas des populations de taille finie est traité par \textcite{Chao2012} et \textcite{Hwang2014}

\subsection{Complétude}

La complétude de l'échantillonnage est la proportion du nombre d'espèces observées: $\xq{s}{}{n}{\ne 0}{}/{S}$.
Elle compte simplement les espèces et ne doit pas être confondue avec la couverture qui somme leurs probabilités: le taux de complétude est toujours très inférieur au taux de couverture parce que les espèces non échantillonnées sont les plus rares.

La complétude du même échantillon d'arbres de forêt tropicale que dans l'exemple précédent peut être estimée en divisant le nombre d'espèces observées par le nombre d'espèces estimées (voir page~\ref{sec:Richesse}):

<<Completeness>>=
# Espèces observées
(Obs <- Richness(Paracou618.MC$Ps))
# Richesse estimée
(Est <- Richness(Paracou618.MC$Ns, Correction = "Jackknife"))
# Complétude
as.numeric(Obs/Est)
@

