% !TeX encoding = UTF-8
% !TeX spellcheck = fr-classique
<<Phylodiversite-parent, echo=FALSE, cache=FALSE>>=
set_parent('Mesures_de_la_Biodiversite.Rnw')
opts_chunk$set(cache=TRUE, warning=FALSE, tidy=TRUE, fig.width=8, fig.height=6, out.width='.8\\maxwidth', tidy.opts=list(blank=FALSE, width.cutoff=60), size="scriptsize")
options(width=60)
# Graphiques postscript
setEPS(horizontal=FALSE, onefile=FALSE, paper="special", family="ComputerModern", encoding="TeXtext.enc", width=8.0, height=6.0)
par(mar=c(0,0,0,0))
library("entropart")
data(Paracou618)
@

\LargeMargins
\selectlanguage{french}
\sisetup{locale = FR}
\chapter{Cadre}

\begin{Essentiel}
  La diversité fonctionnelle ou phylogénétique prend en compte la proximité des espèces entre elles.
  Généralement, la distance entre espèces est évaluée dans l'espace des traits, approximation de l'espace des niches, pour la diversité fonctionnelle et dans un dendrogramme représentant la phylogénie ou la taxonomie pour la diversité phylogénétique.
\end{Essentiel}


\lettrine{L}{es mesures} neutres de la diversité considèrent que toutes les classes auxquelles les objets appartiennent sont différentes, sans que certaines soient plus différentes que d'autres. 
Par exemple, toutes les espèces sont équidistantes les unes des autres, qu'elles appartiennent au même genre ou à des familles différentes. 
Intuitivement, l'idée qu'une communauté de $S$ espèces toutes de genres différents est plus diverse qu'une communauté de $S$ espèces du même genre est satisfaisante.
\textcite{Walker1992} argumente en faveur de la protection de groupes fonctionnels plutôt que de celle de chacune des espèces qui les constitue pour maintenir le bon état des écosystèmes.

Il s'agit donc de caractériser la différence entre deux classes d'objets, puis de construire des mesures de diversité en rapport \autocite{Pielou1975, May1990a, Cousins1991}.
En écologie, ces différences sont fonctionnelles ou phylogénétiques, définissant la diversité fonctionnelle \autocite{Tilman1997} ou la diversité phylogénétique (\foreignlanguage{english}{\emph{phylodiversity}}) \autocite{Webb2006}.

Les premières propositions de ce type d'indices sont dues à \textcite{Rao1982} (voir page~\pageref{sec:Rao}) puis, avec nettement moins de succès, \textcite{Vane-Wright1991} et \textcite{Warwick1995}. 
\textcite{Chave2007} montrent que la diversité neutre prédit mal la diversité phylogénétique (calculée par l'entropie quadratique de Rao).

\pagebreak 

De nombreuses mesures de diversité ont été créées et plusieurs revues permettent d'en faire le tour. \autocite{Ricotta2007}\autocite{Vellend2010}\autocite{Pavoine2011}
Les mesures présentées ici sont les plus utilisées, et notamment celles qui peuvent être ramenées aux mesures classiques en fixant une distance égale entre toutes les espèces.
Le cadre méthodologique dans lequel ces mesures ont été développées est présenté dans ce chapitre, suivi par une revue des nombreuses mesures de diversité fonctionnelles et phylogénétiques de la littérature.
L'entropie phylogénétique et la diversité de Leinster et Cobbold sont ensuite développées en détail, suivies d'une synthèse et de considérations sur la mesure de la diversité individuelle plutôt que spécifique.

Des exemples montrent comment calculer cette diversité, principalement à l'aide du package \emph{entropart}. 
Le package contient les données d'inventaire de deux hectares du dispositif de Paracou et la taxonomie des espèces concernées:

<<entropart>>=
library("entropart")
# Chargement du jeu de données
data(Paracou618)
@

\section{Dissimilarité et distance}

Une similarité ou dissimilarité est toute application à valeurs numériques qui permet de mesurer le lien entre les individus d'un même ensemble ou entre les variables. 
Pour une similarité le lien est d'autant plus fort que sa valeur est grande.

Une dissimilarité vérifie ($k$, $l$ et $m$ sont trois individus):

\begin{itemize}
  \item  La dissimilarité d'un individu avec lui-même est nulle: $d\left(k,k\right)=0$;
  \item  La dissimilarité entre deux individus différents est positive: $d\left(k,l\right)\ge 0$;
  \item  La dissimilarité est symétrique: $d\left(k,l\right)=d\left(l,k\right)$.
\end{itemize}

Une distance vérifie en plus:

\begin{itemize}
  \item  La distance entre deux individus différents est strictement positive: $d\left(k,l\right)=0\Rightarrow k=l$;
  \item  L'inégalité triangulaire: $d\left(k,m\right)\le d\left(k,l\right)+d\left(l,m\right)$.
De nombreux indices de dissimilarité ne vérifient pas cette propriété.
\end{itemize}

Une distance est euclidienne si elle peut être représentée par des figures géométriques. 
On peut rendre toute distance euclidienne par ajout d'une constante \autocite{Lingoes1971, Cailliez1983}. 
Dans R, utiliser \code{is.euclid()} pour vérifier qu'une distance est euclidienne, et \code{cailliez()} ou \code{lingoes()} pour la transformation.

Enfin, une distance est ultramétrique si $d\left(k,m\right)$\break
$\le \max\left(d\left(k,l\right),d\left(l,m\right)\right)$. 
Les distances obtenues en mesurant les longueurs des branches d'un dendrogramme (arbre) résultant d'une classification hiérarchique sont ultramétriques.

\figureMargin{ArbreA1}
  {Arbre phylogénétique ou fonctionnel hypothétique. 
  Rappel de la figure \ref{Arbre}(a).
  5 espèces sont présentes ($S=5$), leurs probabilités notées $p_1$ à $p_5$.
  Les noms des branches sont affichés.
  }
  {\includegraphics[width=\maxwidth]{ArbreA}}


La façon exacte de mesurer les longueurs de branche est illustrée par la Figure~\ref{ArbreA1}: la distance entre les espèces 1 et 2 est $T_1+T_2$, elle est égale à $T_1$ entre les espèces 4 et 5. 
La distance est la hauteur du premier n\oe ud commun.

\section{Distance phylogénétique}
\label{sec:Dphylo}

La façon la plus évidente de définir une distance entre espèces est d'utiliser la taxonomie \autocite{Clarke2001, Warwick2001}, en attribuant une distance arbitraire (par exemple 1) à deux espèces du même genre, une autre (par exemple 2) à deux espèces de la même famille, etc. 
La distance définie est ultramétrique.

La taxonomie peut être remplacée avantageusement par une phylogénie.
La phylogénie idéale contiendrait l'histoire évolutive de toutes les espèces et les distances seraient les temps de divergence depuis le premier ancêtre commun. 
En pratique, les phylogénies sont établies à partir d'un nombre de marqueurs génétiques limités, sans datation précise (mais avec des calages partiels à partir de fossiles), et ne sont pas toujours ultramétriques. 
Elles peuvent prendre en compte chaque individu, sans regroupement par espèce. 
Une méthode pour dater une phylogénie est fournie par \textcite{Chave2007}
\textcite{Zanne2014} fournissent une phylogénie datée de plus de \SI{32000} espèces.
\textcite{Ricotta2012a} montrent sur des exemples que la diversité calculée à partir de phylogénies datées est très corrélée à celle calculée à partir de simples taxonomies.


Dans tous les cas, la distance est une mesure de la divergence évolutive. 
Du point de vue de la biologie de la conservation, chaque espèce accumule une quantité d'évolution, interprétée comme une quantité d'information \autocite{Crozier1997} dont le maximum doit être préservé.

L'entropie phylogénétique (voir page~\pageref{chap:Phyloentropie}) utilise un arbre phylogénétique pour mesurer la diversité.



\section{Distance fonctionnelle}

L'approche fonctionnelle est différente. 
Chaque espèce ou individu est représenté par ses valeurs de traits dans un espace multidimensionnel. 
Le vecteur de traits est considéré comme un proxy de la niche écologique \autocite{Westoby2002}. 
Les individus proches dans l'espace des traits sont donc considérés comme proches écologiquement. 
Les distances entre les points peuvent être calculées directement dans l'espace des traits ou, fréquemment, un arbre est construit par classification automatique hiérarchique.

La première étape consiste donc à choisir un ensemble de traits pertinents et à les mesurer de façon standardisée \autocite{Cornelissen2003}. 
Toute la stratégie relative à la photosynthèse peut être par exemple assez bien résumée par la masse surfacique des feuilles \autocite{Wright2004}, mais, en forêt tropicale, ce trait est décorrélé de la densité du bois \autocite{Baraloto2010}. 
Les valeurs manquantes peuvent être complétées en utilisant toute l'information disponible par MICE (\foreignlanguage{english}{\emph{multiple imputation by chained equations}}) \autocite{VanBuuren2006}, disponible sous R dans le package \code{mice} \autocite{VanBuuren2011}.

\label{Gower}
La prise en compte de variables qualitatives ou de rang et la possibilité de données manquantes pose un problème pratique de construction de la matrice de dissimilarité, traité par \textcite{Gower1971}. 
La formule de Gower, étendue par \textcite{Podani1999} puis \textcite{Pavoine2009b} à d'autres types de variables, calcule la dissimilarité entre deux espèces par la moyenne des dissimilarités calculées pour chaque trait, dont la valeur est comprise entre 0 et 1:

\begin{itemize}
  \item  Pour une variable quantitative, la différence de valeur entre deux espèces est normalisée par l'étendue des valeurs de la variable;
  \item  Les variables ordonnées sont remplacées par leur rang et traitées comme les variables quantitatives;
  \item  Pour des variables qualitatives, la dissimilarité vaut 0 ou 1;
  \item  Les valeurs manquantes sont simplement ignorées et n'entrent pas dans la moyenne.
\end{itemize}

Une matrice de distances entre espèces est construite de cette façon. 
\textcite{Podani2006} suggèrent d'utiliser ensuite une classification hiérarchique par UPGMA \autocite{Sokal1958} qu'ils montrent être la plus robuste (pour le calcul de FD, voir page~\pageref{sec:PDFD}) à l'ajout ou au retrait d'un trait ou d'une espèce.
\textcite{Mouchet2008} suggèrent plutôt d'appliquer toutes les méthodes de classification et de retenir à la fin l'arbre dont la distribution des distances entre espèces dans l'arbre est la plus proche de la distribution des distances dans la matrice de dissimilarités: cette proximité est mesurée par la corrélation cophénétique, c'est-à-dire le coefficient de corrélation entre les valeurs de distances \autocite{Sokal1962, Legendre2012}.
Un arbre consensus \autocite{Felsenstein2004} est souvent plus proche de la matrice de distance.

Un dendrogramme fonctionnel n'a pas d'interprétation aussi claire qu'un arbre phylogénétique qui représente le processus de l'évolution. 
Il peut être interprété comme la représentation à des échelles de plus en plus grossières en allant vers le haut de l'arbre de regroupements fonctionnels dans des niches de plus en plus vastes.

La transformation d'une matrice (non ultramétrique) en dendrogramme déforme la topologie des espèces \autocite{Pavoine2005a, Podani2007} : une mesure de diversité qui utilise directement la matrice est préférable, c'est un intérêt de la  diversité de Leinster et Cobbold (voir page~\pageref{sec:LeinsterCobbold}).
\textcite{Maire2015} ont défini une mesure de qualité d'un espace fonctionnel, \emph{mSD}, comme l'écart quadratique moyen entre les distances fonctionnelles entre espèces dans l'espace utilisé (par exemple les distances cophénétiques dans un dendrogramme fonctionnel) et les distances originales (dans la matrice de distance à partir de laquelle l'arbre a été obtenu).
Dans la matrice originale, les valeurs de traits sont centrées et réduites, et la hauteur du dendrogramme est fixée pour que la distance cophénétique maximale soit égale à la distance originale maximale.

\textcite{Villeger2017} ont montré que l'utilisation de dendrogrammes fonctionnels dans une étude de \textcite{Sobral2016} amène à sous-estimer les changements de niveau de biodiversité liés à l'arrivée d'espèces invasives d'oiseaux.
Dans la très grande majorité des dendrogrammes utilisés, la transformation de la matrice de distance a entraîné un écart moyen de plus de 10\% par rapport aux valeurs originales (une valeur de \emph{mSD}, l'écart quadratique moyen, supérieure à 1\%).
Cette déformation est suffisante pour largement invalider les résultats obtenus.



\section{\'Equivalence des deux diversités}

L'approche fonctionnelle étant particulièrement complexe et lourde à mettre en \oe uvre (notamment pour la mesure des traits sur chaque individu), la tentation a été grande de considérer que la phylogénie contenait plus d'information fonctionnelle que ce qui pouvait être mesuré, et donc de considérer la diversité phylogénétique comme proxy de la diversité fonctionnelle.

Du point de vue théorique, le modèle le plus simple de l'évolution de la valeur d'un trait hypothétique au cours du temps est le mouvement brownien: à chaque génération, la valeur du trait varie un peu, sans mémoire.
Dans ce cadre \autocite{Felsenstein1985}, la variance de la valeur actuelle du trait pour une espèce donnée est proportionnelle à la durée de l'évolution et la covariance entre deux espèces à celle de l'âge de leur ancêtre commun.
Deux espèces proches dans l'arbre phylogénétique décrivant l'évolution doivent donc avoir des valeurs de trait corrélées.

\textcite{Webb2000} a montré que des communautés d'arbres tropicaux avaient une moins grande diversité phylogénétique locale qu'attendue sous l'hypothèse nulle d'une distribution aléatoire des espèces, et a supposé que la cause en était le filtrage environnemental local, agissant sur les traits et observables par la phylogénie, sous l'hypothèse de conservation phylogénétique des traits fonctionnels. 
La discipline appelée \emph{écologie phylogénétique des communautés} cherche encore à comprendre quels traits sont conservés et lesquels sont convergents \autocite{Cavender-Bares2009}.

\textcite{Swenson2009} ont montré que la relation entre les deux diversités était faible. 
L'utilisation de la diversité phylogénétique comme proxy de la diversité fonctionnelle n'est pas satisfaisante \autocite{Pavoine2011}. Pour optimiser la conservation, les deux aspects de la diversité, souvent divergents, doivent être pris en compte \autocite{Devictor2010}.

\section{Typologie des mesures}

\`A partir de la littérature \autocite{Ricotta2007, Pavoine2011}, une typologie des mesures de diversité émerge. 
Elle étend les notions classiques de richesse et équitabilité.

La richesse est l'accumulation de classes différentes dans les mesures classiques. 
Dans un arbre phylogénétique, la longueur des branches représente un temps d'évolution: la richesse en est la somme. 
FD et PD sont des mesures de richesse.

\figureFW{Pavoine2011}
  {Régularité contre irrégularité. 
Les arbres de A à D sont de plus en plus irréguliers. 
L'arbre A, parfaitement régulier, est le cadre des mesures classiques de la diversité. 
La phylogénie étant donnée, trois vecteurs d'abondance (P1 à P3) sont de moins en moins réguliers : dans les cas C et D, la régularité maximale n'est pas obtenue pour des effectifs identiques, mais en augmentant les effectifs des espèces originales (voir Maximum théorique, page~\pageref{MaxTheorique}). 
La figure est issue de \cite[][fig.~1]{Pavoine2011}.
}
  {\includegraphics[width=\maxwidth]{Pavoine2011}
}

La régularité mesure la façon dont les espèces occupent uniformément l'espace des niches \autocite{Pavoine2011}. 
Cette notion est simple dans un espace multidimensionnel (par exemple, l'espace des traits fonctionnels). 
Dans un arbre phylogénétique (Figure~\ref{Pavoine2011}), la régularité de l'arbre \autocite{Mooers1997} est un premier critère, complété éventuellement par les abondances. 
Dans un arbre parfaitement régulier, la régularité se réduit à l'équitabilité.

Les mesures de divergence sont des fonctions croissantes de la dissimilarité entre les espèces, généralement considérées par paires. 
Certaines sont pondérées par les abondances, d'autres non. 
Dans un arbre parfaitement régulier, l'indice de Simpson est une mesure de divergence pondérée. 
Ces mesures sont influencées par la richesse et la régularité.

Face à la profusion des mesures de diversité fonctionnelle, \textcite{Ricotta2005d}, en complément de \textcite{Solow1994} établit un certain nombre d'axiomes:
\begin{enumerate}
  \item Monotonicité d'ensemble: la diversité ne doit pas diminuer quand une espèce est ajoutée avec une faible probabilité (qui ne modifie pas la structure de la communauté existante), quelles que soient ses caractéristiques fonctionnelles;
  \item Jumelage \autocite{Weitzman1992}: l'introduction d'une espèce identique à une espèces existante ne doit pas augmenter la diversité. De façon moins triviale, une espèce infiniment proche ne doit pas augmenter la diversité: il s'agit donc d'un axiome de continuité dans l'espace des niches.
  \item Monotonicité de distance: la diversité ne doit pas diminuer quand la distance entre espèces est augmentée.
  \item Décomposabilité: les mesures de divergence doivent être décomposables en diversité $\alpha$, $\beta$ et $\gamma$, ce qui implique leur concavité par rapport aux probabilités.
\end{enumerate}

L'entropie phylogénétique permet d'unifier ces notions, mais de nombreuses mesures ont été proposées.
Elles sont détaillées au chapitre suivant.


\chapter{Mesures particulières}

\begin{Essentiel}
  De nombreuses mesures de diversité fonctionnelle ou phylogénétique ont été développées pour combiner le mieux possible la richesse et la régularité de la distribution des espèces dans l'espace des niches ou la phylogénie.
  Certaines (PD, FD, l'entropie quadratique de Rao, $H_p$ et $I_1$) seront unifiées au chapitre suivant dans le cadre de l'entropie phylogénétique.
\end{Essentiel}


\lettrine{U}{n certain} nombre de mesures de diversité phylogénétiques a émergé dans la littérature. 
Elles sont passées en revue ici, en commençant par la diversité fonctionnelle envisagée dans l'espace multidimensionnel des traits.
Les sections suivantes envisagent les espèces dans un arbre phylogénétique.

\section{Richesse, équitabilité et divergence fonctionnelle}

\textcite{Mason2005} postulent que la diversité fonctionnelle peut être abordée dans trois dimensions indépendantes (\textcite{Jost2010} montrera que l'indépendance n'est pas assurée):
\begin{itemize}
  \item la richesse fonctionnelle, qui indique l'étendue de l'espace des niches fonctionnelles occupé par la communauté;
  \item l'équitabilité de la distribution des espèces dans ces niches (appelée régularité par \textcite{Pavoine2011});
  \item la divergence fonctionnelle, qui mesure comment la distribution des espèces dans l'espace des niches maximise la variabilité des caractéristiques fonctionnelles dans la communauté et combine richesse et équitabilité.
\end{itemize}

\textcite{Schleuter2010} font une revue des mesures utilisées dans ce cadre.
Les notations des indices utilisées ici sont les leurs.

Différents traits numériques sont connus pour toutes les espèces de la communauté.
La matrice $\matrixsym{X}$ les contient: l'élément $x_{t,s}$ est la valeur moyenne du trait $t$ pour l'espèce $s$.
On note $\vectorsym{T}_s$ le vecteur des valeurs moyennes de chaque trait de l'espèce $s$.

\subsection{Richesse fonctionnelle}

\subsubsection{\'Etendue fonctionnelle}

L'étendue fonctionnelle \autocite{Mason2005} mesure l'étendue des valeurs d'un trait occupée par une communauté, normalisée par l'étendue maximale possible:
\begin{equation}
  \mathit{FR}_R = \dfrac{\max_s(x_{t,s}) - \min_s(x_{t,s})}{X_{t,max} - X_{t,min}},
\end{equation}

où $\max_s(x_{t,s})$ est la valeur maximale pour toutes les espèces de la matrice de la valeur du trait $t$, $X_{t,max}$ est sa valeur maximale absolue (les notations sont identiques pour les minima).
Les extrêmes absolus peuvent être ceux de l'ensemble des communautés comparées.
Ils sont toujours sous-estimés: il est toujours possible théoriquement de trouver des valeurs plus extrêmes en augmentant l'effort d'échantillonnage.
L'étendue fonctionnelle peut être moyennée sur plusieurs traits.

Schleuter et al. développent l'indice $\mathit{FR}_{Is}$ pour prendre en compte la variabilité intraspécifique et les valeurs de traits non occupées par des espèces dans l'étendue fonctionnelle.
Les valeurs de traits individuelles sont nécessaires: l'étendue des valeurs d'un trait est définie comme l'union des étendues des valeurs de chaque espèce. 


\figureMargin{Schleuter2010}
{
  Fonction d'appartenance de l'espace des niches de Schleuter et al., en une dimension \autocite[Figure issue de][Appendix B]{Schleuter2010}.
  $x$, en ordonnée, est la valeur du trait considéré.
  Chaque espèce est considérée comme un ensemble flou dans l'espace des traits.
  Quatre espèces sont représentées, avec leur fonction d'appartenance $f_s(x)$.
  Le volume de l'espace des traits occupé, $\mathit{FR}_{Im}$, est obtenu en intégrant les fonctions d'appartenance: c'est la zone grisée de la figure.
}
{
  {\includegraphics[width=\maxwidth]{Schleuter2010}}
}


\subsubsection{Volume de niches}

La définition de la niche écologique de \textcite{Hutchinson1957} est l'hypervolume, dans l'espace des ressources environnementales, qu'une espèce peut occuper.
L'espace des traits fonctionnels peut être considéré comme une approximation de l'espace des ressources.
Le volume de l'enveloppe convexe de l'espace des traits occupé par la communauté (\foreignlanguage{english}{\emph{convex hull volume}}) est donc une mesure de richesse fonctionnelle multidimensionnelle.
La prise en compte des trous, c'est-à-dire la restriction du volume à l'espace réellement occupé à l'intérieur de cette enveloppe, est possible grâce à une méthode d'estimation d'hypervolume plus élaborée, implémentée dans le package \emph{hypervolume} pour R \autocite{Blonder2014}.

De même que pour l'étendue fonctionnelle, Schleuter et al. développent une mesure proche, $\mathit{FR}_{Im}$, prenant en compte la variabilité intraspécifique et les espaces non occupés.
Chaque espèce est supposée occuper un espace autour de sa position moyenne dans l'espace des traits, avec une fonction d'appartenance \autocite{Zadeh1965} gaussienne multidimensionnelle (une représentation unidimensionnelle se trouve en figure~\ref{Schleuter2010}): la fonction d'appartenance, issue de la logique floue, peut être vue comme une densité de probabilité non normalisée.

Les variances et covariances intraspécifiques des traits (rassemblés dans la matrice carrée $\matrixsym{\Sigma}_s$ de dimension $t$ pour chaque espèce $s$) sont nécessaires.
La fonction d'appartenance de l'espèce $s$ dans l'espace des traits est, pour le vecteur $\vectorsym{T}$ de valeur de l'ensemble des traits:
\begin{equation}
  f_s(\vectorsym{T})= e^{-\frac{1}{2} \left(\vectorsym{T}-\vectorsym{T}_s \right)^\top \matrixsym{\Sigma}_s^{-1}  \left(\vectorsym{T}-\vectorsym{T}_s \right)}.
\end{equation}

La richesse fonctionnelle est l'intégrale des valeurs maximales de $f_s$ dans l'ensemble de l'espace des traits:
\begin{equation}
  \mathit{FR}_{Im} = \int \max_s\left(f_s(\vectorsym{T}) \right) \mathop{d\vectorsym{T}}.
\end{equation}

Après transformation de la matrice de distance en dendrogramme fonctionnel, éventuellement sous la forme d'un arbre-consensus\autocite{Mouchet2008}, la longueur totale des branches (FD)\autocite{Petchey2002} est une autre mesure de richesse multidimensionnelle.



\subsection{Equitabilité fonctionnelle}

L'équitabilité fonctionnelle, ou régularité \autocite{Pavoine2011}, rend compte de l'homogénéité de l'occupation des niches. 

L'indice d'équitabilité de \textcite{Mouillot2005a}, que les auteurs nomment \og indice de régularité fonctionnelle\fg{}, est inspiré de l'indice d'équitabilité de Bulla (page~\pageref{eq:Bulla}).
C'est un indice unidimensionnel: un seul trait est pris en compte.
Les espèces sont classées par valeur croissante du trait.
L'équitabilité maximale est obtenue si l'écart entre deux valeurs de traits est proportionnel aux abondances cumulées des deux espèces.
La statistique fondamentale est appelée équitabilité pondérée (\foreignlanguage{english}{\emph{weighted evenness}}).
Pour l'intervalle entre l'espèce $s$ et l'espèce $s+1$:

\begin{equation}
  \mathit{EW}_{s} = \frac{T_{s+1}-T_{s}}{N_{s+1}+N_{s}}.
\end{equation}

Cette valeur est normalisée: $\mathit{PEW}_{s}=\nicefrac{\mathit{EW}_{s}}{\sum_s{\mathit{EW}_{s}}}$.
Sa valeur de $\mathit{PEW}_{s}$ attendue pour le maximum d'équitabilité est $\nicefrac{1}{(S-1)}$.
L'indice est celui de Bulla, appliqué aux $S-1$ intervalles entre espèces:

\begin{equation}
  \mathit{FE}_{s} = \sum_{s=1}^{S-1}{\min(\mathit{PEW}_{s},\frac{1}{S-1})}.
\end{equation}


L'indice $\mathit{FE}_{s}$ a été étendu pour être multidimensionnel par \textcite{Villeger2008a}.
L'arbre recouvrant de longueur minimum (\foreignlanguage{english}{\emph{minimum spanning tree}}) est d'abord calculé à partir des distances euclidiennes entre les espèces dans l'espace des traits: il s'agit de l'arbre de longueur totale minimale reliant tous les points.
La longueur des branches est ensuite traitée de la même façon que $\delta T_s$ précédemment.

Un autre indice, ${\Lambda}^+$ \autocite{Clarke2001}, mesure la variance des distances entre paires d'espèces:

\begin{equation}
  {\Lambda}^+ =\frac{\sum_s{\sum_t{{\left(d_{s,t}-\hat{d}\right)}^2}}}{S\left(S-1\right)}.
\end{equation}


Comme le montrent \textcite{Merigot2011}, les mesures de régularité n'ont absolument pas les mêmes propriétés que les mesures de diversité: elles peuvent par exemple augmenter quand on retire des espèces originales.


\subsection{Divergence fonctionnelle}

Les mesures de divergence fonctionnelle décrivent la variabilité de position des espèces dans l'espace des traits.
Ce sont tout simplement des mesures de diversité au sens classique du terme.

Quand un seul trait est considéré, la mesure la plus simple est sa variance.
\textcite{Mason2003} effectuent une transformation logarithmique de la valeur du trait et pondèrent le calcul de la variance par les probabilités $p_s$.
Ils transforment finalement le résultat en son arc-tangente pour qu'il soit compris entre 0 et 1.

Schleuter et al. proposent d'utiliser la différence entre le troisième et le premier quartile de la valeur du trait, normalisée par son étendue maximale possible.

FAD a été proposé par \textcite{Walker1999}, à partir d'une matrice de distances dans l'espace des traits. 
$d_{s,t}$ est la distance entre deux espèces indicées par $s$ et $t$, alors:

\begin{equation}
  \mathit{FAD}=\sum_s{\sum_t{d_{s,t}}}.
\end{equation}

FAD est très sensible au nombre d'espèces.
Sa version normalisée, MFAD \autocite{Schmera2009} est

\begin{equation}
  \mathit{MFAD}=\frac{\sum_s{\sum_t{d_{s,t}}}}{S}.
\end{equation}

Les deux indices violent l'axiome de jumelage.
\`A un facteur de normalisation près, ce sont des cas particuliers de l'indice de Rao pour des effectifs égaux.

Le calcul sous R est simple avec un arbre au format \code{phylog} d'\emph{ADE4} :

<<MFAD>>=
Tree <- Paracou618.Taxonomy
(FAD <- sum(Tree$Wdist^2/2))
(MFAD <- FAD/length(Tree$leaves))
@


\textcite{Kader2007} regroupent les valeurs de trait par catégories et calculent l'entropie de Simpson des catégories.

Enfin, \textcite{Villeger2008a} utilisent la distance euclidienne moyenne des espèces au centre de gravité de la communauté plutôt que la variance.
Précisément, le centre de gravité de la communauté (sans pondération par les fréquences) est calculé.
La distance euclidienne de l'espèce $s$ au centre de gravité est $dG_s$; la moyenne pour toutes les espèces $\bar{dG}$.
L'écart moyen des individus de la communauté à la distance moyenne est $\Delta d=\sum_s{p_s(dG_s - \bar{dG})}$.
L'écart moyen absolu est $\Delta |d|=\sum_s{p_s|dG_s - \bar{dG}|}$

L'indice est
\begin{equation}
  \mathit{FD}_{m} = \frac{\Delta d + \bar{dG}}{\Delta |d| +\bar{dG}}.
\end{equation}

Sa forme lui permet d'être compris entre 0 et 1.

\textcite{Laliberte2010} généralisent $\mathit{FD}_{m}$ en proposant l'usage de n'importe quelle dissimilarité entre espèces, obtenue à partir de la méthode de Gower (vue page \pageref{Gower}), autorisant des variables qualitatives et des données manquantes, au-delà de la seule distance euclidienne entre traits quantitatifs.
Ils fournissent le package \emph{FD} pour calculer leur indice $\mathit{FDis}$ et ceux de 
\textcite{Villeger2008a}.



\section{Originalité, richesse et équitabilité phylogénétique}

La littérature de la diversité phylogénétique s'est intéressée tôt à l'originalité taxonomique des espèces parce que les questions traitées concernaient la conservation (intéressée par la valeur de l'héritage évolutif \autocite{Faith2008}).

\subsection{Mesures spécifiques d'originalité}

\textcite{Vane-Wright1991} définissent la distinction taxonomique (\foreignlanguage{english}{\emph{taxonomic distinctness}}) $\mathit{TD}_s$ de chaque espèce comme l'inverse du nombre de n\oe uds entre elle et la racine de l'arbre phylogénétique, normalisé pour que $\sum_s{\mathit{TD}_s} = 1$.
Dans l'arbre de la figure~\ref{ArbreA4}, les valeurs de TD non normalisées sont $\nicefrac{1}{2}$ pour les deux premières espèces et $\nicefrac{1}{3}$ pour les trois autres: la racine de l'arbre est comptabilisée dans le nombre de n\oe uds.
Les valeurs de $\mathit{TD}_s$ sont respectivement $\nicefrac{1}{4}$ et $\nicefrac{1}{6}$ après normalisation.

\figureSC{ArbreA4}
{
  Arbre phylogénétique ou fonctionnel hypothétique.
  L'arbre comprend 5 espèces dont les probabilités sont notées $p_s$, 3 périodes de durées $T_k$ délimitées par les n\oe uds.
  Les branches sont notées $b$ et indicées par la période à laquelle elles se terminent et un numéro d'ordre.
  La légende complète se trouve en figure~\ref{Arbre}.
}
{
  \includegraphics[width=.8\maxwidth]{ArbreA}
}

La particularité évolutive \autocite{Isaac2007} (\foreignlanguage{english}{\emph{evolutive distinctiveness}}, $\mathit{ED}_s$) de l'espèce $s$ est la somme de la longueur des branches qui la relient à la racine de l'arbre, partagées entre tous les descendants de chaque branche.
Pour l'espèce 3 de la figure~\ref{ArbreA4}, $\mathit{ED}_3$ est égal à $l(b_{1,3})$, la longueur de la branche terminale propre à l'espèce 3, plus un tiers de la longueur de la branche qui relie la racine de l'arbre à la polytomie dont l'espèce 3 est issue.
Clairement, la diversité phylogénétique PD (section~\ref{sec:PDFD}) est la somme des particularités évolutives de toutes les espèces de l'arbre.


\subsection{Originalité taxonomique de Ricotta}
\label{sec:OrigTax}

\figureSC{HurlbertCFig}
{
  Contribution des espèces à l'indice de Hurlbert.
  Les contributions de 4 espèces d'une communauté à l'indice sont représentées en fonction de la taille de l'échantillon $n$.
  Les fréquences des espèces sont lisibles pour $n=1$: une espèce fréquente (probabilité égale à 0,7, supérieure à $\nicefrac{1}{S}$), deux espèces peu fréquentes (0,19 et 0,1), et une espèce rare (0,01).
  Quand $n$ est assez grand, toutes les contributions tendent vers $\nicefrac{1}{S}=\nicefrac{1}{4}$ (ligne horizontale).
}
{
  <<HurlbertCFig, echo=FALSE, results='hide'>>=
  <<HurlbertCCode>>
  @
}

\textcite{Ricotta2004b} construit un indice paramétrique (permettant de donner plus ou moins d'importance aux espèces rares) à partir de l'espérance du nombre d'espèces tirées dans un échantillon de taille $n$ fixée (l'indice de \textcite{Hurlbert1971}):

\begin{equation}
  {\mathbb E}\left( \xq{{S}}{}{n}{}{} \right)
  = \sum_s{\left[ 1-\left( 1-p_s \right)^n  \right]}.
\end{equation}

Ricotta pondère cette espérance par l'originalité taxonomique de chaque espèce, notée $w_s$ et normalise la mesure:
\begin{equation}
  \xq{{T}}{n}{}{}{}
  = \frac{\sum_s{w_s \left[ 1-\left( 1-p_s \right)^n  \right]}}{{\mathbb E}\left( \xq{{S}}{}{n}{}{} \right)}.
\end{equation}

L'originalité taxonomique est définie comme la distance phylogénétique moyenne entre l'espèce $s$ et les autres: $w_s=\nicefrac{\sum_s{d_{s,t}}}{S-1}$.

\textcite{Weikard2006} montrent que cette définition de $w_s$ ne permet pas de satisfaire l'axiome de monotonicité d'ensemble.
La définition correcte de $w_s=\sum_s{d_{s,t}}$, validée par \textcite{Ricotta2006}.

L'interprétation de $\xq{{T}}{n}{}{}{}$ est plus intuitive en inversant la logique de sa construction.

$w_s$ est l'originalité de l'espèce $s$.
$\nicefrac{[1-(1-p_s)^n]}{{\mathbb E}(\xq{{S}}{}{n}{}{})}$ est la contribution de l'espèce $s$ à l'espérance du nombre d'espèces, comprise entre 0 et 1. 
$\xq{{T}}{n}{}{}{}$ est donc l'originalité moyenne des espèces de la communauté, pondérée par la contribution de chaque espèce à l'espérance du nombre d'espèces observé, dans un échantillon de taille $n$.
Cette contribution est présentée en figure~\ref{HurlbertCFig}
\verbfootnote{Code R pour la figure:
  <<HurlbertCCode, eval=FALSE>>=
  Ps <- c(0.7, 0.19, 0.1, 0.01)
  S <- length(Ps)
  nRange <- 1:500
  # Indice de Hurlbert
  ESn <- c(1, sapply(nRange[-1], function(n) Hurlbert(Ps, n)))
  # Préparation du graphique
  Xlab <- "Taille de l'échantillon"
  Ylab <- "Contribution des espèces"
  plot(x=nRange, y=c(rep(0,length(nRange)-1),max(Ps)), type = "n", 
       xlab=Xlab, ylab=Ylab, log="x")
  # Tracé des courbes
  sapply(1:S, function(s) lines(nRange, sapply(nRange, 
                function(n) (1-(1-Ps[s])^n))/ESn, lty=s))
  abline(h=1/(S))
  @
}.
Quand $n=1$, c'est simplement la fréquence des espèces.
Quand $n$ augmente, le poids des espèces fréquentes (dont la proabilité est supérieure à $\nicefrac{1}{S}$) diminue alors que celui des espèces intermédiaires augmente.
Ce dernier atteint $\nicefrac{1}{{\mathbb E}(\xq{{S}}{}{n}{}{})}$ (une espèce est échantillonnée à coup sûr dès que l'échantillon est assez grand) d'autant plus rapidement que $p_s$ est grand.
Il baisse ensuite alors que les espèces rares atteignent à leur tour progressivement leur poids maximal.

Quand $n \to +\infty$, le numérateur tend vers FAD, et le dénominateur tend vers le nombre d'espèces: $\xq{{T}}{n}{}{}{}$ tend vers MFAD.


\subsection{Richesse phylogénétique}

La particularité taxonomique moyenne \autocite{Warwick1995} (\foreignlanguage{english}{\emph{Average Taxonomic Distinctiveness, AvTD}}) est la distance moyenne dans l'arbre entre deux espèces choisies au hasard.
C'est donc l'équivalent taxonomique de MFAD.
La variabilité phylogénétique des espèces \autocite{Helmus2007} (\foreignlanguage{english}{\emph{Phylogenetic Species Variability, PSV}}) est la même mesure, obtenue à partir du modèle d'évolution suivant un mouvement brownien \autocite{Felsenstein1985}.
La distance moyenne entre deux espèces est dans ce cadre proportionnelle à la covariance de leurs traits fonctionnels.
La richesse phylogénétique des espèces, PSR, est PSV multipliée par le nombre d'espèces: c'est l'équivalent taxonomique de FAD.

La diversité FD de Faith (section~\ref{sec:PDFD}), égale à la somme des longueurs des branches de l'arbre, semble avoir fait consensus, d'où un moindre développement des mesures de richesse que dans la littérature fonctionnelle.


\subsection{Indices de Cadotte}

\textcite{Cadotte2010} proposent un ensemble de mesure phylogénétiques: équitabilité, déséquilibre d'abondance et diversité de la particularité evolutive.

\subsubsection{Equitabilité phylogénétique}

Les branches terminales de l'arbre phylogénétique sont ici à la base de la définition de l'équitabilité.
Figure~\ref{ArbreA3}, les branches $b_{1,s}$ sont les segments terminés par une feuille (au bas de l'arbre), c'est-à-dire que leur longueur est la partie de l'arbre que les espèces ne partagent pas.
La mesure d'équitabilité est
\begin{equation}
  \mathit{PAE} = \frac{\mathit{PD} + \sum_s{l(b_{1,s})(n_s-1)}}{\mathit{PD} + (\frac{n}{S}-1)\sum_s{l(b_{1,s})} }.
\end{equation}

\figureMargin{ArbreA3}
{Arbre phylogénétique ou fonctionnel hypothétique. 
  Rappel de la figure \ref{Arbre}(a).
}
{\includegraphics[width=\maxwidth]{ArbreA}
}

$\mathit{PAE}$ vaut 1 quand les espèces sont sont distribuées équitablement pour la longueur des branches.
Une valeur plus grande est obtenue quand les espèces sont concentrées au bout des longues branches, et inversement si $0<\mathit{PAE}<1$.


\subsubsection{Déséquilibre d'abondance}

L'équilibre d'abondance est défini par une distribution aléatoire des espèces par division de l'effectif total à partir de la racine de l'arbre phylogénétique.
En figure~\ref{ArbreA3}, en partant de la racine, la moitié des individus est supposée se répartir sur chaque branche.
\`A la période 2, les effectifs de la branche de gauche se partagent en deux parties égales.
\`A partir du nombre total d'individus de la communauté, $n$, le nombre attendu d'individus $n_s^0$ de l'espèce $s$ est une fraction de $n$ correspondant au nombre de n\oe uds et au nombre de branches partant de chaque n\oe ud.
On note $y_{k,s}$ le nombre de branches partant du n\oe ud ancestral de l'espèce $s$ à la période $k$, s'il existe, $y_{k,s}=1$ sinon:
\begin{equation}
  n_s^0 = \frac{n}{\prod_{k=2}^{K}{y_{k,s}}}.
\end{equation}

En figure~\ref{ArbreA3}, pour l'espèce 3, $y_{1,3}=3$ (l'espèce est issue d'une polytomie), $y_{2,3}=1$ (absence de n\oe ud) et $y_{3,3}=2$ (la racine de l'arbre est dichotomique).
On s'attend donc à ce que l'espèce 3 soit représentée par un sixième des individus.

L'indice de déséquilibre d'abondance mesure l'écart à cette distribution théorique:
\begin{equation}
  \mathit{IAC} = \frac{\sum_s{|n_s - n_s^0|}}{\nu}.
\end{equation}

$\nu$ est le nombre de n\oe uds de l'arbre (3 dans l'exemple de la figure~\ref{ArbreA3}).


\subsubsection{Diversité de la particularité évolutive}

L'entropie de Shannon peut être appliquée pour mesurer la diversité des particularités évolutives:
\begin{equation}
  H_{\mathit{ED}} = -\sum_s{\frac{\mathit{ED}_s}{\mathit{PD}} \ln\frac{\mathit{ED}_s}{\mathit{PD}}}.
\end{equation}

L'équitabilité des particularités évolutives est celle de Pielou :

\begin{equation}
  E_{\mathit{ED}} = \frac{H_{\mathit{ED}}}{\ln{S}}.
\end{equation}

Ces mesures ne prennent pas en compte les abondances des espèces.
Pour y remédier, il suffit d'ajouter une période de durée nulle à chaque feuille de l'arbre, correspondant à une polytomie entre les $n_s$ individus de chaque espèce.
La particularité évolutive $\mathit{AED}_s$ des individus de l'espèce $s$, est calculée en partageant la longueur de chaque branche ancestrale entre le nombre d'individus qui en descendent (et non le nombre d'espèces).
Alors $\mathit{PD} = \sum_s{n_s \mathit{AED}_s}$.
L'entropie devient
\begin{equation}
  H_{\mathit{AED}} = -\sum_s{\frac{n_s \mathit{AED}_s}{\mathit{PD}} \ln\frac{n_s \mathit{AED}_s}{\mathit{PD}}}
\end{equation}
et l'équitabilité correspondante est
\begin{equation}
  E_{\mathit{AED}} = \frac{H_{\mathit{AED}}}{\ln{N}}.
\end{equation}

Ces indices ne mesurent pas la diversité phylogénétique au sens des autres mesures présentées dans ce chapitre.
Ils mesurent la diversité de le particularité évolutive, autrement dit du temps d'évolution accumulé par chaque espèce ou chaque individu.
Pour un nombre d'espèces fixé, $E_{\mathit{ED}}$ atteint son maximum quand les valeurs de $\mathit{ED}_s$ sont toutes identiques.
Un arbre phylogénétique composé d'une seule branche depuis la racine terminé par une polytomie de longueur nulle portant toutes les espèces correspond à cette description.
Dans cet exemple, les espèces ont une divergence évolutive nulle, mais $E_{\mathit{ED}} = S$, son maximum possible.


\section{Diversité de Scheiner}

\textcite{Scheiner2012} développe un cadre unifié pour mesurer la diversité spécifique, phylogénétique ou fonctionnelle, séparément ou simultanément.
L'idée générale est que toute quantité partagée par les espèces (le nombre d'individus, le temps d'évolution accumulé, la taille des niches écologique) peut être traduite en nombre de Hill.

La diversité spécifique est simplement $\xq{D}{q}{}{}{}$. Scheiner la note $\xq{D}{q}{}{}{}(A)$, pour diversité d'abondance.

La diversité phylogénétique $\xq{D}{q}{}{}{}(P)$ ne prend pas en compte les abondances mais mesure la diversité de la divergence évolutive des espèces. 
La divergence totale dans un arbre phylogénétique (pas forcément ultramétrique) est la longueur totale des branches (c'est-à-dire FD). 
Elle est répartie entre toutes les espèces: la longueur de chaque branche (représentant une quantité d'évolution) est partagée à parts égales entre les espèces qui en descendent.
La divergence de l'espèce 1 de la Figure~\ref{Arbre}, page~\pageref{Arbre}, est $T1+T2$, la longueur de la branche terminale, plus $\nicefrac{T3}{2}$, parce que la branche est partagée par les espèces 1 et 2. 
La divergence de l'espèce 1, est donc $L_1 = T1+T2+\nicefrac{T3}{2}$. 
La part de la divergence de l'espèce $s$ est $l_s = \nicefrac{L_s}{FD}$.
La diversité phylogénétique est le nombre de Hill des divergences:

\begin{equation}
  \xq{D}{q}{}{}{} = {\left(\sum^S_{s=1}{l_s^q}\right)}^{\frac{1}{1-q}}.
\end{equation}

La diversité fonctionnelle $\xq{D}{q}{}{}{}(F)$ est la diversité des tailles des niches. La taille de la niche est définie par Scheiner comme le volume de l'hypersphère (dans l'espace des traits fonctionnels de dimension $m$) centrée sur chaque espèce dont le rayon est la moitié de la distance à l'espèce la plus proche pour que les sphères ne se superposent pas.
Une meilleure définition \autocite{Presley2014} de la taille de la niche est la somme des distances aux autres espèces: $t_s = \sum_t{d_{s,t}}$. La part de chaque espèce est $f_s=\nicefrac{t_s}{\sum_t{t_t}}$ et la définition de la diversité fonctionnelle est

\begin{equation}
  \xq{D}{q}{}{}{}(T) = {\left(\sum^S_{s=1}{f_s^q}\right)}^{\frac{1}{1-q}}.
\end{equation}

La diversité peut prendre en compte plusieurs composantes, pas exemple l'abondance et la phylogénie pour définir

\begin{equation}
  \xq{D}{q}{}{}{}(AP) = {\left(\sum^S_{s=1}{\left(\frac{n_s L_s}{\sum^S_{t=1}{n_t L_t}}\right)^q}\right)}^{\frac{1}{1-q}}.
\end{equation}

La diversité d'abondance et phylogénétique est la diversité des divergences pondérées par les effectifs des espèces. 
La mesure de biodiversité de Scheiner, incluant les trois composantes, est

\begin{equation}
  \xq{D}{q}{}{}{}(APF) = {\left(\sum^S_{s=1}{\left(\frac{n_s L_s t_s}{\sum^S_{t=1}{n_t L_t t_t}}\right)^q}\right)}^{\frac{1}{1-q}}.
\end{equation}

Son interprétation est moins immédiate.
Chaque espèce est associée à une fraction d'une des trois dimensions de la diversité (abondance, temps d'évolution cumulé, taille des niches).
Elle occupe un parallélépipède de dimensions $(p_s, l_s, f_s)$ dans le cube de dimension 1 qui les contient toutes.
Cette représentation ne donne pas d'importance particulière à l'abondance, et peut être appliquée à un nombre quelconque de dimensions.
La mesure de biodiversité est la diversité des volumes occupés par les espèces, normalisés par leur somme (qui n'est pas égale à 1).

En se limitant à deux dimensions pour la lisibilité, la figure~\ref{ScheinerPsfsFig}\verbfootnote{
  Code R:
  <<ScheinerPsfsCode, eval=FALSE>>=
  # Probabilités
  Ps <- Paracou618.MC$Ps[Paracou618.MC$Ps>0]
  Ps <- sort(Ps, decreasing = TRUE)
  # Fréquences cumulées
  PsCum <- cumsum(Ps)
  Xgauche <- c(0, PsCum)
  Xdroite <- c(PsCum, 1)
  # Matrice de distances fonctionnelles
  DistanceMatrix <- as.matrix(Paracou618.dist)
  # Mise en correspondance de la matrice et du vecteur de probabilités
  DistanceMatrix <- DistanceMatrix[names(Ps), names(Ps)]
  # Taille des niches
  ts <- rowSums(DistanceMatrix)
  fs <- ts/sum(ts)
  # Fréquences cumulées
  fsCum <- cumsum(fs)
  Ybas <- c(0, fsCum)
  Yhaut <- c(fsCum, 1)
  # Rectangles occupés par chaque espèce
  plot(c(0, 1), c(0, 1), asp=1, type="n", xlab="Fréquence", ylab="Niche")
  rect(Xgauche, Ybas, Xdroite, Yhaut)
  @
} présente les rectangles correspondant à la diversité d'abondance et fonctionnelle occupés par les espèces de la méta-communauté \code{Paracou618}, classées par fréquences décroissantes.

\figureSC{ScheinerPsfsFig}
{Rectangles de surface fréquence $\times$ taille de niche des espèces de la méta-communauté \code{Paracou618}. La diversité de Scheiner $\xq{D}{q}{}{}{}(AF)$ est la diversité de leur surface.}
{
  <<ScheinerPsfsFig, echo=FALSE, results='hide', fig.width=6, fig.height=6>>=
  <<ScheinerPsfsCode>>
  @
}

La diversité d'abondance et fonctionnelle est la diversité de la surface des rectangles:
<<ScheinerDqAF>>=
Surface <- Ps*fs
Rs <- Surface/sum(Surface)
Diversity(Rs, q=2)
@

Le profil de diversité d'abondance et fonctionnelle est en figure~\ref{ProfilDqAFFig}
\verbfootnote{
  Code R:
  <<ProfilDqAFCode, eval=FALSE>>=
  plot(CommunityProfile(Diversity, Rs), xlab="Ordre de diversité", ylab="Diversité")
  lines(CommunityProfile(Diversity, Ps), lty=2)
  lines(CommunityProfile(Diversity, fs), lty=3)
  @
}. 

\figureSC{ProfilDqAFFig}
{Profil de diversité d'abondance et fonctionnelle de Scheiner de la méta-communauté \code{Paracou618}. Pointillés longs : diversité d'abondance; pointillés courts : diversité fonctionnelle; trait plein : diversité d'abondance et fonctionnelle.}
{
  <<ProfilDqAFFig, echo=FALSE, results='hide'>>=
  <<ProfilDqAFCode>>
  @
}


La notion de diversité phylogénétique ou fonctionnelle traitée par Scheiner est assez différente de celles vues précédemment parce qu'elle considère toutes les dimensions de façon symétrique: l'ordre de diversité, $q$, s'applique à toutes les dimensions.
Si $q$ est grand, les espèces dont le produit des dimensions de la diversité est petit (que l'espèce soit rare, ait une divergence phylogénétique faible ou une niche étroite) sont négligées, alors que $q$ n'affecte que la fréquence dans le cadre de la phylodiversité $\xq{\bar{D}}{q}{}{}{}$ ou la banalité pour $\xq{D}{q}{\matrixsym{Z}}{}{}$.


\section{Diversité de Solow et Polasky}

\textcite{Solow1994} relient la richesse fonctionnelle ou phylogénétique à la probabilité de trouver au moins une espèce intéressante (par exemple, capable de fournir une molécule utile) dans une communauté.

Les distances entre espèces sont supposées connues, qu'elles soient fonctionnelle, phylogénétique ou autre.
La probabilité qu'une espèce quelconque soit intéressante est fixée à $p$, par exemple à partir de l'expérience passée (si une espèce criblée sur 100 fournit une molécule utile, $p=1\%$).
En absence d'information sur les espèces, $p$ est \emph{a priori} identique pour toutes mais on suppose une corrélation entre les probabilités dépendant de la distance entre les espèces.
Formellement, une fonction de similarité entre les espèces $s$ et $t$ est définie: $z_{s,t}=f(d_{s,t})$.
Cette fonction est décroissante entre 1 (quand la distance est nulle) et 0 (à distance infinie); par exemple $f(d_{s,t}) = e^{-u d_{s,t}}$ où $u$ est une constante strictement positive.
La matrice $\matrixsym{Z}$ réunit les éléments $z_{s,t}$.

On définit ensuite la variable de Bernoulli $B_s$ (d'espérance $p_s$) qui vaut 1 si l'espèce $s$ est intéressante.
$z_{s,t}$ est, par construction du modèle, la corrélation entre $B_s$ et $B_t$: deux espèces très proches ont la même probabilité d'être intéressante, deux espèces très éloignées ont des probabilités indépendantes.
La probabilité qu'au moins une espèce soit intéressante est minorée par $p^2 \matrixsym{1}_S' \matrixsym{Z}^{-1} \matrixsym{1}_S$, où $\matrixsym{1}_S$ est le vecteur de longueur $S$ ne contenant que des 1, $'$ indique la transposée et $\matrixsym{Z}^{-1}$ est la matrice inverse de $\matrixsym{Z}$ (son existence est garantie puisque $\matrixsym{Z}$ est une matrice de variance-covariance).
La valeur de $p$ est incertaine et sans grand intérêt.

$V = \matrixsym{1}_S' \matrixsym{Z}^{-1} \matrixsym{1}_S$ est la mesure de diversité de Solow et Polasky.
Elle rend compte de la dispersion des espèces : moins les espèces sont similaires, plus la probabilité que l'une d'elle au moins soit intéressante est élevée, conditionnellement au nombre d'espèces et à $p$.
Si les espèces sont infiniment éloignées les unes des autres, $\matrixsym{Z}$ est la matrice identité et la diversité est égale à la richesse: $V$ est donc un nombre effectif d'espèces, c'est-à-dire le nombre d'espèces totalement dissimilaires nécessaires pour obtenir la diversité observée.
\`A l'opposé, si toutes les espèces sont identiques, $\matrixsym{Z}$ ne contient que des 1 et la diversité vaut 1.


\section{FD et PD}
\label{sec:PDFD}

\figureSC{Arbre}
  {Arbre phylogénétique ou fonctionnel hypothétique. 
(a) Arbre complet. 
5 espèces sont présentes ($S=5$). 
Une période de l'arbre est définie entre deux n\oe uds successifs: l'arbre contient $K=3$ périodes. 
Les hauteurs des périodes sont notées $T_k$. 
\`A chaque période correspond un arbre plus simple (b pour la période 2, c pour la période 3) dans lequel les espèces originales sont regroupées. 
Le nombre de feuilles de ces arbres est noté $L_k$. 
Les probabilités pour un individu d'appartenir à une feuille sont notées $u_{k,l}$.}
  {\includegraphics[width=\maxwidth]{Arbre}}

Si la dissimilarité entre les espèces est représentée par un dendrogramme, les indices de diversité les plus simples sont la diversité phylogénétique \autocite{Faith1992} et sa transposition, la diversité fonctionnelle \autocite{Petchey2002}.

\'Etant donné un arbre contenant toutes les espèces ou tous les individus étudiés, PD ou FD sont égaux à la somme de la longueur des branches (Figure~\ref{Arbre}: $\mathit{PD}=5\times T_1 + 3\times T_2 + 2\times T_3)$.
Si les n\oe uds de l'arbre phylogénétique sont datés, PD peut être considéré comme une accumulation de temps d'évolution par la communauté étudiée: \textcite{Sol2017} montrent par exemple que les milieux urbanisés ont un déficit de 450 millions d'années d'évolution dans les communautés d'oiseaux relativement aux environnements naturels voisins.

Dans le cas particulier ou toutes les branches sont de longueur 1, c'est-à-dire que toutes les espèces sont liées à la même racine (on dira que l'arbre est parfaitement régulier), PD et FD sont égales à la richesse spécifique.

Le package \emph{entropart} fournit la fonction \code{PDFD}:

<<PDFD>>=
# Vecteur des probabilités
Ps <- Paracou618.MC$Ps
PDFD(Ps, Paracou618.Taxonomy)
@

\textcite{Chao2014b} fournissent un estimateur de PD (ou FD) permettant de l'estimer sans biais pour un échantillon plus petit que celui observé et de façon fiable pour un échantillon de taille double au maximum. Ces estimateurs permettent de tracer des courbes de raréfaction et d'extrapolation.

En même temps que Faith, \textcite{Weitzman1992} a établi une fonction de diversité identique à PD. 
\`A partir d'une matrice de dissimilarités entre espèces, un arbre est construit par la méthode suivante.
Les deux espèces les plus proches sont rassemblées.
L'une d'elles, celle qui diminue le moins la longueur totale des branches de l'arbre final en la retirant, est l'espèce de \emph{lien}, l'autre est l'espèce \emph{représentative} du clade.
L'espèce de lien est retirée et le regroupement poursuivi entre les deux nouvelles espèces les plus proches.
\`A chaque étape, l'espèce de lien est retirée jusqu'au regroupement final entre les deux dernières espèces.
La difficulté est que l'arbre final n'est pas connu aux premiers stades de regroupement donc tous les arbres doivent être testés pour trouver la solution unique.
La diversité est la somme des distances entre les espèces de lien et leur espèce représentative, c'est-à-dire la longueur totale des branches de l'arbre obtenu.
L'application à la conservation est que les espèces représentatives doivent être favorisées par rapport aux espèces de lien; en d'autres termes, les espèces dont les branches sont les plus courtes dans l'arbre sont celles qui apportent le moins de diversité.
Ce résultat est assez évident quand on dispose d'un arbre phylogénétique.
L'originalité de la méthode de Weitzman est de fournir un algorithme pour créer l'arbre à partir d'une matrice de distances qui est cohérent avec la mesure de diversité appliquée.

La mesure de diversité peut être combinée avec une probabilité d'extinction de chaque espèce (à dire d'expert) pour calculer l'espérance de la diversité à une échéance donnée \autocite{Weitzman1993} : $2^S$ arbres peuvent être construit en faisant disparaître certaines des $S$ espèces de la communauté, la probabilité de chaque arbre est calculable à partir des probabilités d'extinction de chaque espèce (supposées indépendantes) et l'espérance de diversité est simplement la moyenne des diversités de chaque arbre pondérée par sa probabilité.
L'espérance de la perte de diversité peut être calculée de façon plus simple \autocite{Witting1995}, comme la moyenne de la longueur des branches pondérée par la probabilité de leur disparition, qui est le produit de la probabilité de disparition de toutes les espèces descendant de la branche.

Diverses optimisations économiques sont possibles, dont le choix des espèces à protéger à partir de l'élasticité de la diversité, c'est-à-dire le gain de diversité entraîné par la diminution de la probabilité de disparition de chaque espèce: les espèces ayant la plus grande élasticité sont celles sur lesquelles les efforts auront les plus grands résultats.



\section{Indice de Rao}
\label{sec:Rao}

L'indice de Rao est une mesure de divergence pondérée. Son utilisation s'est largement développée depuis le début des années 2000 \autocite{Izsak2000}\autocite{Shimatani2001a}\autocite{Botta-Dukat2005}\autocite{Escalas2013} en raison de ses propriétés particulièrement intéressantes.

\subsection{Principe}

\`A partir de relevés fournissant la fréquence de chaque espèce par communauté et d'une matrice de dissimilarité entre paires d'espèces, l'indice de \textcite{Rao1982} donne la dissimilarité moyenne entre deux individus choisis au hasard.

L'indice de Rao est souvent appelé \og entropie quadratique\fg{} en raison de sa forme mathématique.

\subsection{Formalisation}

Les espèces sont prises deux à deux et sont donc notées ici $s'$ et $s''$.

On note $\matrixsym{\Delta}$ la matrice de dissimilarité dont les éléments sont $\delta_{s's''}$, la dissimilarité entre l'espèce $s'$ et l'espèce $s''$. 
Il n'est pas nécessaire à ce stade que $\matrixsym{\Delta}$ soit une distance. 
$\vectorsym{p}$ est le vecteur des probabilités dont $p_{s'}$ et $p_{s''}$ sont des éléments:

L'indice de Rao est

\begin{equation}
  H_{\matrixsym{\Delta}}\left(\vectorsym{p}\right)=\sum_{s'}{\sum_{s''}{p_{s'}}}p_{s''}\delta_{s's''}.
  \label{eq:Rao}
\end{equation}


\subsection{Propriétés}

La définition de la distance est essentielle:

\begin{itemize}
  \item  en fixant $\delta_{s's''}=1$ si deux espèces sont différentes, on obtient l'indice de Simpson. 
Sa valeur peut être interprétée comme la probabilité qu'une paire d'individus choisie au hasard soit de deux espèces différentes;
  \item  Dans un espace unidimensionnel où la valeur $y_s$ associée à l'espèce $s$ est une variable quantitative $Y$, choisir $\delta_{s's''}={{\left(y_k-y_l\right)}^2}/{2}$ rend l'indice de Rao égal à la variance de $Y$.
\end{itemize}

\textcite{Pavoine2005c} ont montré que l'utilisation de distances ordinaires fait que la valeur maximale de l'entropie quadratique pour un effectif donné est obtenue en éliminant les espèces intermédiaires en ne retenant que les espèces extrêmes (le résultat est évident en une dimension: la variance est maximale en ne retenant que les valeurs extrêmes d'un échantillon). 
Ce résultat est contraire aux propriétés attendues d'un indice de diversité. 
Les auteurs ont établi que l'utilisation de distances ultramétriques corrige ce défaut. 
L'indice atteint alors son maximum pour des fréquences d'autant plus grandes que l'espèce est originale \autocite{Pavoine2005a}.

L'estimation empirique de l'indice se fait simplement en estimant les probabilités par les fréquences. 
Le biais d'estimation est très faible \autocite{Marcon2014a} : par analogie avec l'estimateur de l'indice de Simpson, les espèces rares interviennent peu.

\subsection{Calcul sous R}

Le package \emph{entropart} fournit la fonction \code{Rao} :

<<Rao>>=
# Vecteur des probabilités
Ps <- Paracou618.MC$Ps
Rao(Ps, Paracou618.Taxonomy)
@

Le package \emph{ADE4} permet le calcul avec la fonction \code{divc} qui utilise un format différent pour les probabilités et surtout la matrice des racines carrées du double des distances de l'objet \code{phylog} (chaque élément de \code{\$Wdist} vaut $\sqrt{2\delta_{s's''}}$.
Cette particularité d'\emph{ADE4} vient de l'analyse multivariée \autocite{Champely2002}: l'entropie quadratique de Rao peut être représentée dans l'espace euclidien engendré par une matrice de distances $\matrixsym{D}$ entre espèces (par une Analyse en Composantes Principales, PCoA).
L'inertie des points représentants les espèces, précisément la moyenne des carrés des distances entre les espèces et leur centre de gravité (les probabilités $\vectorsym{p}$ des espèces constituent leur poids), est alors égale à l'entropie de Rao $H_{\matrixsym{\Delta}}\left(\vectorsym{p}\right)$, où la matrice de distances $\matrixsym{\Delta}$ est $\dfrac{\matrixsym{D}^{\circ2}}{2}$: les valeurs de  $\matrixsym{\Delta}$ valent la moitié du carré de celles de $\matrixsym{D}$.
Cette représentation est étendue dans la double analyse en composantes principales de \textcite{Pavoine2004} (page~\pageref{sec:RaoDisc}).

Dans \emph{ADE4}, les arbres phylogénétiques sont donc stockés sous la forme d'objets de type \code{phylog} où la matrice des distances (\code{\$Wdist}) est $\matrixsym{D}$ mais les longueurs des branches de l'arbre (\code{\$droot}) correspondent aux valeurs de $\matrixsym{\Delta}$.


<<divc, message=FALSE>>=
library("ade4")
divc(as.data.frame(Ps), Paracou618.Taxonomy$Wdist)
@

\code{divc} peut traiter plusieurs communautés simultanément; \code{Rao} peut être utilisé avec la fonction \code{apply} :

<<divcRao>>=
divc(as.data.frame (Paracou618.MC$Psi), Paracou618.Taxonomy$Wdist)
apply(Paracou618.MC$Psi, 2, Rao, Tree=Paracou618.Taxonomy)
@

\subsection{Maximum théorique}
\label{MaxTheorique}

\textcite{Pavoine2005a} ont défini l'originalité d'une espèce comme sa fréquence maximisant l'entropie quadratique, sachant la matrice de distances entre espèces. 
Les espèces les plus originales sont celles ayant le moins d'espèces proches dans la classification.

L'originalité n'est pas intéressante dans une taxonomie: une phylogénie doit être créée pour illustrer cette notion. 
Le fichier \code{rao.traits.csv} contient une espèce par ligne, identifiée par le champ \code{Code}, et un certain nombre de valeurs de traits en colonnes.

<<Originalite1>>=
# Lecture des données : traits pour 34 espèces
read.csv2 ("http://www.ecofog.gf/IMG/csv/rao.traits.csv", row.names=1, header=T)-> traits
@

Le résultat est un \emph{data frame} nommé \code{traits} à 8 lignes (espèces) et 6 colonnes (traits):

<<Originalite2>>=
# Aperçu
traits[1:4, 1:3]
@

La matrice de distances est créée par classification automatique hiérarchique.

<<Originalite3>>=
# ACP sur les traits foliaires
pcaf <- dudi.pca(traits, scale=T, scannf=FALSE, nf=2)
@

\figureMargin{PCAFFig}
  {Analyse en composante principale des traits foliaires}
  {
<<PCAFFig, echo=FALSE, results='hide', out.width='\\textwidth'>>=
<<PCAFCode>>
@
  }

\code{pcaf} (Figure~\ref{PCAFFig}
\verbfootnote{
Code R:
<<PCAFCode, eval=FALSE>>=
scatter(pcaf)
@
}) est une liste qui contient les résultats de l'ACP, à utiliser pour la classification:

<<Originalite4>>=
# CAH Ward des traits foliaires
hf <- hclust(dist(pcaf$tab), "ward.D")
@

\figureMargin{HclustFig}
  {Arbre phylogénétique issu de la classification automatique.}
  {
<<HclustFig, echo=FALSE, results='hide', out.width='\\textwidth'>>=
<<HclustCode>>
@
  }

Le résultat de la classification est un objet \code{hclust}
(Figure~\ref{HclustFig}
\verbfootnote{
Code R:
<<HclustCode, eval=FALSE>>=
plot(hf, h=-1)
@
} qui doit être transformé en \code{phylog} pour la suite de l'analyse:

<<Originalite5>>=
# Transformation de l'arbre du format hclust au format phylog
phyf <- hclust2phylog(hf)
@


Le résultat est en Figure~\ref{PhylogRaoFig}
\verbfootnote{
  Code R:
  <<PhylogRaoCode, eval=FALSE>>=
  table.phylog(pcaf$tab[names (phyf$leaves),], phyf)
  @
}.

\figureSC[t]{PhylogRaoFig}
  {Présentation de l'arbre phylogénétique avec la contribution de chacune des variables.}
  {
<<PhylogRaoFig, echo=FALSE, results='hide', out.width='\\textwidth'>>=
<<PhylogRaoCode>>
@
  }

La limite des distances ultramétriques est leur tendance à déformer le jeu de points \autocite{Pavoine2005a}. 
Dans cet exemple, les deux premiers axes de l'ACP rendent compte de presque toute l'inertie. 
Le nuage de points est pratiquement contenu dans un plan alors que sa représentation en distance ultramétrique est une hypersphère en 7 dimensions.

Le calcul de l'originalité des espèces utilise la fonction\break
\code{originality}
(Figure~\ref{originalityFig}
\verbfootnote{
Code R:
<<originalityCode, eval=FALSE>>=
dotchart.phylog(phyf, originality(phyf, 5))
@
}
).

\figureMargin{originalityFig}
  {Originalité des espèces.}
  {
<<originalityFig, echo=FALSE, results='hide', out.width='\\textwidth'>>=
<<originalityCode>>
@
  }

La fonction a pour paramètres l'objet \code{phylog} contenant la classification et le numéro de la méthode de calcul à utiliser, 5 pour l'entropie quadratique. 
Sa représentation graphique est faite par \code{dotchart.phylog} :

L'originalité ne repose que sur l'arbre, pas sur la fréquence des espèces.

Si la distance utilisée n'est pas ultramétrique, il existe plusieurs distributions possibles d'espèces qui maximisent la diversité \autocite{Pavoine2009}, le concept d'originalité n'a pas de sens dans ce cas.

La valeur de l'entropie quadratique dépend de la hauteur de l'arbre.
Plusieurs normalisations ont été proposées: par sa valeur maximale ou par la diversité de Simpson (correspondant à un arbre dont toutes les espèces seraient équidistantes) \autocite{Ricotta2005c}, ou en fixant la hauteur de l'arbre à 1\autocite{Marcon2014b}.



\section{Diversité et moyenne}

\textcite{Garnier2004} définissent la moyenne pondérée d'un trait à l'échelle de la communauté (CWM: \foreignlanguage{english}{\emph{Community Weigthed Mean}}), simplement égal à la moyenne de la valeur du trait pondérée par la fréquence des espèces :

\begin{equation}
  \mathit{CWM} = \sum_s{p_s y_s}.
\end{equation}

CWM n'est pas une mesure de diversité fonctionnelle, bien qu'il ait été utilisé parfois en tant que tel \autocite{Lavorel2008}, mais une mesure de la composition de la communauté.
CWM peut être étendu à plusieurs traits : le vecteur formé par les valeurs de CWM pour chaque trait correspond au centre de gravité de la communauté représentée dans l'espace des traits.
L'entropie quadratique de Rao mesure la dispersion des espèces autour de ce point: les deux mesures se complètent donc \autocite{Ricotta2011}.


\section{Variations sur l'entropie quadratique}

\textcite{Izsak2011} proposent deux variantes de l'indice de Rao dans lesquelles la distance entre espèces dépend de leurs probabilités:

\begin{equation}
  L_1 = \sum_{s}{\sum_{t}{p_{s}p_{t}{\left(p_{s}-p_{t}\right)}^2}};
\end{equation}

\begin{equation}
  L_2=\sum_{s}{\sum_{t}{p_{s}p_{t}{\left(\ln{p_{s}}-\ln{p_{t}}\right)}^2}}.
\end{equation}

Ces indices sont proposés pour leurs propriétés mathématiques, assurant l'existence de sa décomposition, sans support écologique bien établi.

$\matrixsym{\Delta}$ est la matrice de dissimilarité dont les éléments sont $\delta_{s,t}$, la dissimilarité entre l'espèce $s$ et l'espèce $t$.
\textcite{Guiasu2011, Guiasu2012} proposent l'indice $\mathit{{GS}_{D}}$ pour ses propriétés mathématiques et fournissent sa décomposition:

\begin{equation}
  \label{eq:Guiasu}
  \mathit{{GS}_{D}}=\sum_{s}{\sum_{t}{\delta_{s,t}p_{s}}}p_{t}\left(1-p_{s}p_{t}\right).
\end{equation}


\section{Diversité fonctionnelle de Chiu et Chao}

\textcite{Chiu2014b} proposent de pondérer l'entropie quadratique par la distance entre les paires d'espèces et obtiennent un nombre de Hill permettant de mesurer la diversité fonctionnelle à partir d'une matrice de dissimilarité:

\begin{equation}
  \xq{D}{q}{}{}{}\left(Q\right)
  = \left[\sum_s{\sum_t{\frac{\delta_{s,t}}{Q}\left(p_s p_t\right)^q}}\right]^\frac{1}{2\left(1-q\right)};
\end{equation}

\begin{equation}
  \xq{D}{1}{}{}{}\left(Q\right)
  = e^{\frac{1}{2}\left[\sum_s{\sum_t{p_s p_t\frac{\delta_{s,t}}{Q}\ln{p_s p_t}}}\right]}.
\end{equation}

La notation $\xq{D}{q}{}{}{}(Q)$ fait référence à l'entropie quadratique $Q=\xq{\bar{H}}{2}{}{}{}(T)$. 
Une approche complémentaire est développée ci-dessous. 
Chiu et Chao notent que $\mathit{{GS}_{D}} = Q - \xq{D}{q}{}{}{}(Q)$.

La définition de Chiu et Chao revient à calculer l'entropie des paires d'individus à partir de la fonction d'information
$$I(p_s p_t) = \ln_q[\nicefrac{(\nicefrac{\delta_{s,t}}{Q})^{\nicefrac{1}{1-q}}}{p_s p_t}]$$
pour $q \ne 1$ et 
$$I(p_s p_t) = \ln[\nicefrac{1}{(p_s p_t)^{\nicefrac{\delta_{s,t}}{Q}}}]$$
pour $q=1$.
Le nombre effectif de paires est $[\xq{D}{q}{}{}{}(Q)]^2$. Le nombre effectif d'espèces est donc $\xq{D}{q}{}{}{}(Q)$.

Le nombre effectif de paires est le nombres de paires équifréquentes dont la distance entre les deux espèces est $Q$. Le problème de cette approche est que les paires constituées de la même espèce doivent aussi avoir une distance $\delta_{s,s}$ égale à $Q$. Chiu et Chao considèrent ce point comme la possibilité de prendre en compte la variabilité intraspécifique, mais elle doit être identique à la variabilité interspécifique, ce qui n'est pas très convaincant. En absence de variabilité intraspécifique, Chiu et Chao redéfinissent la distance de référence: $\delta_{s,s}=0$ et $\delta_{s,t}=(\nicefrac{D}{D-1})Q$. Il n'est donc pas possible de comparer le nombre effectif d'espèces de deux communautés différentes puisque la définition même du nombre effectif dépend de la diversité, ce qui invalide cette définition de la diversité fonctionnelle.

Enfin, cette définition de la diversité ne respecte pas le principe de \textcite{Solow1993} selon lequel le remplacement d'une partie des effectifs d'une espèce par le même nombre d'individus d'une espèce différente mais fonctionnellement identique ne doit pas faire varier la diversité \autocite{Botta-Dukat2017}.



\section{$H_p$ et $I_1$}
\label{sec:HpI1}

Simultanément, \textcite{Pavoine2009a} et \textcite{Allen2009} ont proposé la généralisation de l'indice de Shannon à la diversité phylogénétique. 
La présentation de Allen et al. est donnée ici, celle de Pavoine et al., plus générale, sera détaillée dans le paragraphe suivant.

\figureMargin{ArbreA2}
  {Arbre phylogénétique ou fonctionnel hypothétique. 
  Rappel de la figure \ref{Arbre}(a).
  }
  {\includegraphics[width=\maxwidth]{ArbreA}}


\'Etant donné une phylogénie, comme celle de la Figure~\ref{ArbreA2}, on définit une branche $b_{k,l}$ comme un segment terminé par une feuille (au bas de l'arbre) ou un n\oe ud (dans l'arbre). 
$k$ indique la période de l'arbre à laquelle la branche se termine, $l$ le numéro d'ordre.
Une branche n'existe que si elle se termine effectivement par un n\oe ud ou une feuille: il n'y a pas de branche $b_{2,1}$ par exemple. 
Sa probabilité $p(b_{k,l})$ est la somme des probabilités des feuilles de la branche, c'est-à-dire $u_{k,l}$, et $l(b)$ est sa longueur. 
Sur la figure, la branche commençant en haut de l'arbre et se terminant au n\oe ud réunissant les espèces 3 à 5 a une valeur $p(b_{2,3})$ égale à la somme des probabilités d'occurrence des espèces 3 à 5 alors que $p(b_{1,1})$ est seulement la probabilité de l'espèce 1. 
Leurs longueurs respectives sont $T_2+T_3$ et $T_1+T_2$. 
L'arbre possède 7 branches.

L'indice d'entropie phylogénétique est

\begin{equation}
  H_p =-\sum_{b}{l(b)p(b)\ln{p}(b)}.
\end{equation}

Dans un arbre parfaitement régulier, toutes les branches sont de longueur 1 et $H_p$ est l'indice de Shannon.



\chapter{Entropie phylogénétique}
\label{chap:Phyloentropie}

\begin{Essentiel}
  L'entropie phylogénétique est la moyenne de l'entropie HCDT le long d'un arbre phylogénétique.
  Son estimation est simplement celle de l'entropie HCDT à chaque période de l'arbre.
  Elle va de pair avec la diversité phylogénétique qui est son nombre effectif d'espèces, c'est-à-dire le nombre d'espèces équiprobables, dans un arbre où toutes les espèces descendraient d'un ancêtre unique, dont l'entropie serait la même que celle de la communauté réelle.
  Dans un tel arbre, la diversité phylogénétique se réduit à la diversité neutre.
\end{Essentiel}

\lettrine{L}{'entropie} HCDT peut être étendue pour définir une mesure de diversité prenant en compte l'histoire évolutive des espèces.

\section{Généralisation de l'entropie HCDT}

\textcite{Pavoine2009} découpent l'arbre phylogénétique en périodes. 
\`A partir de la racine de l'arbre, une nouvelle période est définie à chaque ramification d'une branche quelconque. 
Les débuts et fins de périodes sont notés $t_k$, la racine de l'arbre est fixée à $t_0=0$. 
L'arbre est ultramétrique.

Nous suivrons plutôt les notations de \textcite{Chao2010} en numérotant les périodes à partir du présent et en notant $T_k$ leur durée. 
Figure~\ref{Arbre}, la première période se termine quand les branches des espèces 3 à 5 se rejoignent. 
L'arbre comprend $K=3$ périodes.

\figureMargin{ArbreA5}
{Arbre phylogénétique ou fonctionnel hypothétique. 
  Rappel de la figure \ref{Arbre}(a).
  5 espèces sont présentes ($S=5$), leurs probabilités notées $p_1$ à $p_5$.
  Les noms des branches sont affichés.
}
{\includegraphics[width=\maxwidth]{ArbreA}}

L'entropie HCDT ($\xq{H}{q}{}{}{}$ de l'équation (\ref{eq:HCDT})) est calculée à chaque période. 
Figure~\ref{ArbreA5}, à la deuxième période ($T_2$), l'arbre a trois feuilles, avec des probabilités égales à celle des espèces 1 et 2 et la somme de celles des espèces 3 à 5. 
$\xq{H}{q}{}{}{}$ peut être calculée avec ces valeurs de probabilités. 
On notera cette valeur d'entropie $\xq{H}{q}{}{}{k}$ où $k$ est le quantième de la période.

L'indice $I_q$ de Pavoine et al. est la somme des $\xq{H}{q}{}{}{k}$ pondérée par la durée de chaque période. 
Nous le normalisons par la hauteur totale de l'arbre ($T$) pour définir $\xq{\bar{H}}{q}{}{}{}(T)$:

\begin{equation}
  \xq[]{\bar{H}}{q}{}{}{} \left( T \right)=\sum_{k=1}^K{\frac{T_k}{T}\xq[\;]{H}{q}{}{}{k}}
\label{eq:Hbarq}.
\end{equation}

Dans un arbre parfaitement régulier, toutes les branches sont de longueur 1, il n'y a qu'une seule période, et $I_q=\xq[\,]{H}{q}{}{}{}$.

\textcite{Shimatani2001} puis \textcite{Ricotta2005e} avaient montré que l'indice de Rao est la somme pondérée sur chaque période de l'indice de Simpson, c'est-à-dire l'égalité (\ref{eq:Hbarq}) pour le cas particulier $q=2$.

Les indices $\xq{\bar{H}}{q}{}{}{}(T)$ généralisent les mesures d'entropie classique à la diversité phylogénétique: $T[\xq{\bar{H}}{0}{}{}{}(T)+1]$ est égal à PD ou FD, $\xq{\bar{H}}{1}{}{}{}(T)$ est $H_p$ et $^2{\bar{H}(T)}$ est l'indice de Rao. 
On peut les interpréter intuitivement comme une somme pondérée par la longueur des périodes des valeurs de l'entropie à chaque période. 
\`A la dernière période (près des feuilles), toutes les classes sont présentes, la diversité est donc maximale. 
En remontant dans l'arbre, les classes se confondent et la diversité diminue progressivement. 
Deux classes peu distantes, comme les espèces 3 à 5 de la Figure~\ref{ArbreA5}, apportent peu de diversité supplémentaire par rapport à une situation où les deux espèces seraient confondues (et leurs effectifs ajoutés), contrairement aux espèces 1 et 2.

\section{Estimation}

La correction du biais d'estimation applicable à l'entropie généralisée l'est aussi à chaque période de l'arbre. 
Les biais sont de moins en moins importants quand on se rapproche de la racine de l'arbre: il est de moins en moins probable de ne pas observer une classe quand les classes sont de plus en plus vastes. 


Le package \emph{entropart} fournit la fonction \code{PhyloEntropy} pour calculer $\xq{\bar{H}}{q}{}{}{}(T)$ à partir d'un vecteur de probabilité ou d'abondances. 
Dans le dernier cas, la correction de \code{Tsallis} est appliquée à chaque période.

Exemple: le package contient les données d'inventaire de deux hectares du dispositif de Paracou et la taxonomie des espèces concernées. 
Le calcul de l'indice de Rao, corrigé du biais d'estimation utilise le code suivant:

<<bcRao>>=
data(Paracou618)
PhyloEntropy(Paracou618.MC$Ns, 2, Paracou618.Taxonomy)
@

La fonction retourne la valeur de $\xq{H}{q}{}{}{k}$ dans chaque intervalle (l'arbre est ici une taxonomie espèce-genre-famille, correspondant aux limites des périodes (\code{Cuts}) 1, 2 et 3 dont l'entropie va en décroissant) et la valeur de $\xq{\bar{H}}{q}{}{}{}(T)$.

\section{Entropie et diversité}

La diversité phylogénétique est le nombre d'espèces équifréquentes et dont la distance à toutes les autres dans la phylogénie est maximale, dont l'entropie serait égale à l'entropie observée.

La possibilité de choisir comme distance de référence entre espèces une valeur inférieure à la distance maximale est discutée par \textcite{Ricotta2014a} pour la diversité fonctionnelle: sa signification biologique est liée à l'espace fonctionnel disponible pour la communauté, qui peut être trop réduit pour permettre la coexistence d'espèces dont la dissimilarité serait maximale.

L'entropie $\xq{\bar{H}}{q}{}{}{}(T)$ peut être transformée en diversité \autocite{Marcon2014a} de la même façon que $\xq{D}{q}{}{}{} = e^{\xq{H}{q}{}{}{}}$:

\begin{equation}
  \xq{\bar{D}}{q}{}{}{}\left(T\right)=e^{\xq{\bar{H}}{q}{}{}{}\left(T\right)}_q.
\end{equation}

Le nombre effectif d'espèces de l'entropie de Rao, $\xq{\bar{D}}{2}{}{}{}(T)=\nicefrac{1}{[1-\xq{\bar{H}}{2}{}{}{}(T)]}$ a été établi par \textcite{Ricotta2009}.

\textcite{Chao2010} obtiennent ce résultat sans recourir explicitement à l'entropie, mais en faisant le même calcul:

\begin{equation}
  \xq{\bar{D}}{q}{}{}{} \left( T \right)
  =\left( \sum_b{\frac{l(b)}{T} p(b)^q} \right)^{\frac{1}{1-q}}.
\label{eq:Dbarq}
\end{equation}

La somme est sur l'ensemble des branches de l'arbre, défini de façon identique à celle de \textcite{Allen2009}, page \pageref{sec:HpI1}.

Les entropies ont un comportement linéaire: elles s'additionnent tout au long de l'arbre pour donner $\xq{\bar{H}}{q}{}{}{}(T)$. 
Les diversités $\xq{D}{q}{}{}{k}$ calculées à chaque période ne peuvent pas être sommées sur le modèle de l'équation (\ref{eq:Hbarq}): $\xq{\bar{D}}{q}{}{}{}(T)$ n'est \emph{pas} la moyenne pondérée des diversités aux différentes périodes, sauf dans le cas particulier $q=1$ où, comme pour la décomposition de l'indice de Shannon, il en est la moyenne géométrique pondérée.

La fonction \code{PhyloDiversity} de \emph{entropart} permet de calculer $\xq{\bar{D}}{q}{}{}{}(T)$ avec ou sans correction de biais, selon qu'elle traite un vecteur d'abondances ou de probabilités. 
\`A la suite de l'exemple précédent, les résultats sont présentés sous forme de diversité au lieu d'entropie:

<<bcPhyloDiversity>>=
PhyloDiversity(Paracou618.MC$Ns, 2, Paracou618.Taxonomy)
@



\section{Diversité individuelle}

La construction de la diversité fonctionnelle ou phylogénétique n'implique pas de regrouper les individus par espèces : chaque catégorie peut se réduire à un individu si des données individuelles moléculaires ou de traits sont disponibles.

Le regroupement des individus en une espèce revient simplement à considérer leur distance comme nulle. 
Diviser une espèce en deux espèces infiniment proches revient seulement à créer une période supplémentaire dans l'arbre, de longueur infinitésimale; en d'autres termes, la mesure de diversité est continue face au regroupement. 
Cette propriété permet de limiter les conséquences du problème de l'espèce : séparer les individus d'une espèce en deux espèces proches dans l'arbre n'a que peu d'effet sur la diversité.



\section{Arbres non ultramétriques}

\figureMargin{Chao2010}
  {Arbre phylogénétique hypothétique non ultramétrique \autocite[][figure 1b]{Chao2010}.}
  {\includegraphics[width=\maxwidth]{Chao2010}}    


\textcite{Chao2010} définissent la diversité phylogénétique selon l'équation (\ref{eq:Dbarq}) quelle que soit la forme de l'arbre, y compris s'il n'est pas ultramétrique. 
Dans ce cas, $T$ est remplacé par $\bar{T}$, la longueur moyenne des branches pondérée par la fréquence des espèces. 
Cette généralisation est très discutable: son sens n'est pas clair sur le plan de la mesure de la diversité au-delà du parallélisme de la forme mathématique.

L'arbre de la Figure~\ref{Chao2010} peut être découpé en périodes mais les deux premières ($T_1$: seule l'espèce 2 est présente; $T_2$: les espèces 1 et 2 sont présentes) sont incomplètes au sens où la somme des probabilités n'y est pas égale à 1 donc ${\left(\sum{p^q_i}\right)}^{\frac{1}{1-q}}$ ne définit pas une diversité à ces périodes.

\textcite{Pavoine2009} traitent en détail les résultats aberrants que cause un arbre non ultramétrique dans le cas particulier de l'entropie de Rao. 
\textcite{Leinster2012} montrent qu'un arbre non ultramétrique implique que la dissimilarité entre les espèces dépende de leur fréquence, ce qui est contradictoire avec le cadre dans lequel la diversité phylogénétique a été définie.

Dans l'état actuel des connaissances, aucune méthode n'est applicable de façon satisfaisante aux arbres non ultramétriques.




\chapter{Diversité de Leinster et Cobbold}
\label{sec:LeinsterCobbold}


\begin{Essentiel}
  La diversité de Leinster et Cobbold est l'inverse de la banalité moyenne des espèces, qui est elle-même la similarité moyenne d'une espèce aux autres.
  Elle va de pair avec l'entropie de Ricotta et Szeidl, dont la fonction d'information est le logarithme déformé de l'inverse la banalité.
  La diversité peut être calculée directement à partir de la distance entre espèces, sans recourir à un dendrogramme intermédiaire qui déformerait la topologie des espèces.
\end{Essentiel}

\lettrine{\`A}{partir} de la théorie mathématique des catégories \autocite{Leinster2013}, \textcite{Leinster2012} ont proposé une mesure de diversité applicable à une communauté dont la position des espèces dans un espace multidimensionnel euclidien est connue.
C'est donc une mesure applicable à la diversité fonctionnelle.

\section{Définitions}

\textcite{Leinster2012} proposent une unification des mesures de diversité à partir de la définition de la banalité des espèces. 
Une matrice carrée de dimension égale au nombre d'espèces, $\matrixsym{Z}$, décrit par ses valeurs $z_{s,t}$ la similarité entre l'espèce $s$ et l'espèce $t$ comprises entre 0 et 1 ($z_{s,s}=1$).

La banalité d'une espèce $s$ est définie par $\sum_t{p_t z_{s,t}}$, c'est-à-dire la moyenne pondérée de sa similarité avec toutes les autres espèces: au minimum $p_s$ si elle est totalement différente des autres (approche de la diversité neutre, $\matrixsym{Z}$ est la matrice identité $\matrixsym{I}_s$), au maximum 1 si toutes les espèces sont totalement similaires ($\matrixsym{Z}$ ne contient que des 1). 
Une espèce rare totalement différente des autres est peu banale.

La moyenne généralisée d'ordre $r$ \autocite{Hardy1952}, \foreignlanguage{english}{\emph{generalized mean}} ou \foreignlanguage{english}{\emph{power mean}} en anglais, est définie pour une distribution de valeurs de $x_s$ dont la probabilité d'occurrence est $p_s$ par

\begin{equation}
\bar{x}={\left(\sum_s{p_s x^r_s}\right)}^{\frac{1}{r}}.
\end{equation}

\figureMargin{MoyenneHardyFig}
  {Moyenne généralisée d'ordre $r$ (en abscisse) d'une distribution uniforme de 100 valeurs tirées entre 0 et 1. 
La moyenne arithmétique 0,5 est obtenue pour $r=1$. 
La moyenne généralisée tend vers la plus petite valeur (près de 0) quand $r\to -\infty$, et vers la plus grande valeur (près de 1) quand $r\to +\infty$.}
  {
<<MoyenneHardyFig, echo=FALSE, results='hide', out.width='\\textwidth'>>=
<<MoyenneHardyCode>>
@
  }

La moyenne généralisée se réduit à la moyenne arithmétique pondérée pour $r=1$. 
Elle donne un fort poids aux petites valeurs de $x_s$ dans la moyenne pour les faibles valeurs de $r$ (qui peuvent être négatives), et un fort poids aux grandes valeurs quand $r$ est grand (Figure~\ref{MoyenneHardyFig}
\verbfootnote{Le code R nécessaire pour réaliser la figure est:
  <<MoyenneHardyCode, eval=FALSE>>=
  X <- runif(100)
  # La moyenne n'est pas définie à r=0, décalage de 10^-8
  r <- seq(-5, 10, .1) + 1E-8
  plot(y=sapply(r, function(r) (mean(X^r))^(1/r)), x=r,
       type="l", ylab="Moyenne")
  abline(h=.5, lty=2); abline(v=1, lty=2)
  @
}).

La banalité peut s'écrire sous forme matricielle en notant $\vectorsym{p}$ le vecteur des probabilités $p_s$, on note alors ${\left(\vectorsym{Zp}\right)}_s=\sum_t{p_{t}z_{s,t}}$. 


La banalité moyenne des espèces de la communauté est calculée en prenant $r=q-1$:

\begin{equation}
  \left(\overline{{\vectorsym{Zp}}}\right)
  = {\left(\sum_s{p_s{\left(\vectorsym{Zp}\right)}^{q-1}_s}\right)}^{\frac{1}{q-1}}.
\end{equation}


La diversité de la communauté est simplement l'inverse de la banalité moyenne des espèces:

\begin{equation}
  \xq{D}{q}{\matrixsym{Z}}{}{}={\left(\sum_s{p_s{\left(\vectorsym{Zp}\right)}^{q-1}_s}\right)}^{\frac{1}{1-q}}.
  \label{eq:Dqz}
\end{equation}

$\xq{D}{q}{\matrixsym{Z}}{}{}$ converge vers $\xq{D}{1}{\matrixsym{Z}}{}{}$ quand $q$ tend vers 1:

\begin{equation}
  \xq{D}{1}{\matrixsym{Z}}{}{}=\frac{1}{\prod_s{{\left(\vectorsym{Zp}\right)}^{p_s}_s}}.
\end{equation}


\section{Diversité neutre}

Leinster et Cobbold montrent que la diversité HCDT est un cas particulier de $\xq{D}{q}{\matrixsym{Z}}{}{}$, pour la matrice identité:

\begin{equation}
  \xq{D}{q}{}{}{}=\xq[\,]{D}{q}{\matrixsym{I}}{}{}.
\end{equation}


\section{Diversité non neutre}

Une mesure de diversité non neutre est obtenue en utilisant une matrice $\matrixsym{Z}$ qui contient l'information sur la similarité entre les espèces. 
La dissimilarité entre espèces peut être obtenue à partir des arbres. 
L'exemple suivant utilise les données du calcul d'originalité, page~\pageref{MaxTheorique}. 
Pour un arbre de classe \code{hclust}, la fonction \code{cophenetic} fournit une demi-matrice de distances (classe \code{dist}).

<<DqZ1>>=
print(cophenetic(hf), digits = 4)
@

La matrice doit être normalisée puis transformée en matrice de similarité. 
Une transformation simple est 1 moins la dissimilarité (préalablement normalisée pour être comprise entre 0 et 1):

<<DqZ2>>=
Dis <- cophenetic(hf)
print((Z <- 1-as.matrix(Dis/max(Dis))), digits = 4)
@

La diversité peut être calculée par la fonction \code{Dqz} de \emph{entropart}:

<<DqZ3>>=
# Vecteur contenant 8 espèces...
(read.csv2("http://www.ecofog.gf/IMG/csv/rao.effectifs.csv", row.names=1, header=T)-> effectifs)
Ps <-rowSums(effectifs)/sum(effectifs)
Dqz(Ps, q=2, Z)
@

Dans le cas particulier $q=2$, $\xq{D}{2}{\matrixsym{Z}}{}{}$ est égal à $\xq{\bar{D}}{2}{}{}{}(T)$:

<<DqZ4>>=
PhyloDiversity(Ps, q=2, phyf)$Total
@

Mais ce n'est pas le cas en général.

\section{Entropie de Ricotta et Szeidl}

\textcite{Ricotta2006b} ont montré une similitude entre les entropies de Shannon et de Rao en généralisant l'entropie de Shannon en deux temps. 
Tout d'abord en remarquant que la probabilité d'occurrence d'une espèce est 1 moins la somme de celle des autres, d'où

\begin{equation}
  \xq{H}{1}{}{}{} = -\sum_s{p_s\ln\left(1-\sum_{t\ne s}{p_t}\right)}.
\end{equation}

$1-\sum_{t\ne s}{p_t}$ est la banalité de l'espèce $s$ si on mesure la diversité neutre. 
De façon plus générale, ${(\vectorsym{Zp})}_s$ peut exprimer cette banalité. 
Enfin, l'entropie HCDT peut généraliser l'entropie de Shannon pour définir une mesure $Q_{\alpha}$ que nous noterons $\xq{H}{q}{\matrixsym{Z}}{}{}$ pour la cohérence de nos notations ($q=\alpha$):

\begin{equation}
  \xq{H}{q}{\matrixsym{Z}}{}{} = \sum_s{p_{s}\ln_q{\frac{1}{\left(\vectorsym{Zp}\right)_s}}}.
\end{equation}

De façon plus rigoureuse, on peut remarquer que ${(\vectorsym{Zp})}_s$ décroît quand $p_s$ décroît parce que la similarité d'une espèce avec elle-même est maximale. 
Une entropie définie à partir d'une fonction d'information de $p_s$ reste donc une entropie quand on utilise la même fonction d'information sur ${(\vectorsym{Zp})}_s$: la fonction reste décroissante et vaut 0 pour $p_s=1$ puisque ${(\vectorsym{Zp})}_s=1$ dans ce cas. 
$\xq{H}{q}{\matrixsym{Z}}{}{}$ est donc bien une entropie. 
La fonction d'information $\ln_q(1/p_s)$ de l'entropie HCDT (\ref{eq:EntropieHCDT}) est simplement remplacée par $\ln_q(1/{(\vectorsym{Zp})}_s)$.

L'entropie de Ricotta et Szeidl étend l'entropie HCDT en utilisant une fonction d'information plus générale, dépendant de la banalité de l'espèce plutôt que de sa seule probabilité, les deux étant égales dans le cas particulier de la diversité neutre. 
L'ordre de la diversité $q$ permet de donner un plus ou moins grand poids aux espèces banales (et non aux espèces fréquentes: $p_s$ est à la puissance 1). 
La fréquence et la banalité se confondent seulement pour la diversité neutre.

Le logarithme d'ordre $q$ de $\xq{D}{q}{\matrixsym{Z}}{}{}$ est $\xq{H}{q}{\matrixsym{Z}}{}{}$:

\begin{equation}
  \ln_q{\xq{D}{q}{\matrixsym{Z}}{}{}} = \xq[\,]{H}{q}{\matrixsym{Z}}{}{}.
\end{equation}



\section{Définition de la similarité}

La transformation d'une matrice de dissimilarité en une matrice de similarité nécessite une fonction strictement décroissante, dont le résultat est compris entre 0 et 1. 
La plus simple est
$$z_{s,t} = 1 - \nicefrac{d_{s,t}}{\max{(d_{s,t})}}.$$
Leinster et Cobbold argumentent en faveur d'une transformation exponentielle négative, déjà utilisée par \textcite{Nei1972}.

\figureMargin{LineaireZpsqFig}
  {Approximation de ${(\vectorsym{Zp})}_{s}^{q-1}$ par son développement limité au premier ordre pour $q=1.5$ en haut ($r=q-1$) et $q=0.5$ en bas.}
  {
  %  \begin{tabular}{cc}
  <<LineaireZpsqFig1, echo=FALSE, results='hide', out.width='\\textwidth'>>=
  <<LineaireZpsqCode1>>
  @
%  &
  <<LineaireZpsqFig2, echo=FALSE, results='hide', out.width='\\textwidth'>>=
  <<LineaireZpsqCode2>>
  @
%  \end{tabular}
  }

Le problème majeur de la diversité $\xq{D}{q}{\matrixsym{Z}}{}{}$ est qu'elle fournit souvent des valeurs presque indépendantes de $q$ quand on l'applique à une matrice de similarité fonctionnelle \autocite{Chiu2014b}. 
De nombreux exemples, y compris dans l'article original de Leinster et Cobbold, montrent une très faible décroissance de la diversité de $q=0$ à $q=2$. 
Ce n'est pas un problème théorique mais numérique. 
Si la banalité de l'espèce $s$ est proche de 1, sa puissance $q$ peut être approchée par son développement limité au premier ordre :
$${(\vectorsym{Zp})}_{s}^{q-1} \approx 1 + (q-1)[{(\vectorsym{Zp})}_{s} - 1].$$ 
Cette approximation linéaire implique que
$$\sum_s{p_s{\left(\vectorsym{Zp}\right)}^{q-1}_s} \approx [\sum_s{p_s{\left(\vectorsym{Zp}\right)}_s}]^{q-1}.$$ 
La puissance $q-1$ disparaît donc dans le calcul de la diversité et l'équation~\ref{eq:Dqz} devient
$$\xq{D}{q}{\matrixsym{Z}}{}{} \approx \bar{z}$$
où $\bar{z} = \sum_s{p_s (\vectorsym{Zp})_s}$.
Dans les faits, cette approximation vaut pour des valeurs de banalité assez éloignées de 1 (Figure~\ref{LineaireZpsqFig}
\verbfootnote{Le code R nécessaire pour réaliser la figure est:
  <<LineaireZpsqCode1, eval=FALSE>>=
  r <- 0.5
  seqZp <- seq(0, 1, 0.001)
  plot(seqZp^r~seqZp, type="l", xlab="x", ylab=expression(x^r))
  abline(a=1-r, b=r, col="red", lty=2)
  @
  <<LineaireZpsqCode2, eval=FALSE>>=
  r <- -0.5
  plot(seqZp^r~seqZp, type="l", xlab="x", ylab=expression(x^r))
  abline(a=1-r, b=r, col="red", lty=2)
  @
}). 
Si une majorité des espèces (au sens de la somme de leurs probabilités respectives) a une banalité supérieure à 0,5, l'approximation linéaire est assez bonne et la moyenne généralisée de la banalité est proche de sa moyenne arithmétique. 
Ce n'est pas un problème pour la comparaison de profils de diversité de communautés différentes calculés à partir de la même matrice de similarité mais l'interprétation de la diversité en termes de nombres effectifs d'espèces dépendant de $q$ n'est pas très intuitive.

La transformation exponentielle négative,
$$z_{s,t} = e^{-u \frac{d_{s,t}}{\max{(d_{s,t})}}},$$
est justifiée par \textcite{Leinster2013}. 
$u$ est une constante positive. 
Plus $u$ est grand, plus la transformation est convexe : les similarités sont tassées vers 0 (Figure~\ref{EchelleFig}
\verbfootnote{Le code R nécessaire pour réaliser la figure est:
  <<EchelleCode, eval=FALSE>>=
  curve(exp(-x), ylim=c(0,1))
  curve(exp(-2*x), lty=2, add=TRUE)
  curve(exp(-10*x), lty=3, add=TRUE)
  @
}). 
Augmenter la valeur de $u$ diminue les similarités et donc la banalité des espèces, ce qui règle (arbitrairement) le problème de la faible sensibilité de la diversité au paramètre $q$.

Du point de vue théorique, l'ordre des valeurs de la matrice des distances est justifié (par les différences entre traits fonctionnels par exemple) mais leur distribution ne l'est pas : elle n'est que la conséquence de la méthode de calcul. 
Le choix de $u$ ne change pas l'ordre des distances mais déforme la distribution des similarités.
La distance étant normalisée, $u$ fixe l'échelle des distances avant la transformation.
\figureMargin{EchelleFig}
  {Transformation des distances (en abscisse) en similarités (en ordonnées) selon la valeur de $u$. 
Trait plein: $u=1$; pointillés longs : $u=2$; pointillés : $u=10$. 
Plus $u$ est grand, plus les similarités sont tassées vers 0.}
  {
  <<EchelleFig, echo=FALSE, results='hide', out.width='\\textwidth'>>=
  <<EchelleCode>>
  @
  }

Leinster relie la valeur de $\xq{D}{q}{\matrixsym{Z}}{}{}$ à la magnitude de l'espace des espèces (espace dans lequel les espèces sont des points dont les distances deux à deux sont décrites par la matrice $\Delta$, qui doit être euclidienne): la magnitude de l'espace est la valeur maximale que peut atteindre la diversité. 
La magnitude est une propriété qui décrit la taille d'un espace dans le cadre de la théorie des catégories. 
Modifier $u$ modifie la magnitude de l'espace selon une relation non triviale : $u$ est un paramètre au même titre que $q$. 
Quand $u \to +\infty$, $\matrixsym{Z} \to \matrixsym{I}_s$: la diversité tend vers la diversité neutre. 
Leinster et Cobbold suggèrent de comparer les profils de diversité en fonction à la fois de $q$ et de $u$.


\section{Estimation}

Comme les autres mesures de diversité, $\xq{D}{q}{\matrixsym{Z}}{}{}$ est sujette au biais d'estimation. 
Deux estimateurs réduisant le biais existent \autocite{Marcon2014e}. 
Le premier utilise la technique de \textcite{Chao2003} déjà vue pour la correction du biais de l'entropie de Shannon (page~\pageref{eq:ChaoShen}). 
L'estimateur de $\xq{H}{q}{\matrixsym{Z}}{}{}$ est

\begin{equation}
  \xq{\tilde{H}}{q}{\matrixsym{Z}}{}{}
  = \sum_s{\frac{\hat{C}\hat{p}_s \ln_q \frac{1}{{\left(\widetilde{\vectorsym{Zp}}\right)}_s}}{1-{\left(1-\hat{C}\hat{p}_s\right)}^n}},
\end{equation}

où

\begin{equation}
  {\left(\widetilde{\vectorsym{Zp}}\right)}_s
  = \sum_t{{\hat{C}\hat{p}}_t z_{s,t}} +\left(1-\hat{C}\right)\bar{z}.
\end{equation}


L'estimateur de la diversité est $\xq{\tilde{D}}{q}{\matrixsym{Z}}{}{}=e^{\xq{\tilde{H}}{q}{\matrixsym{Z}}{}{}}_q$. 

L'autre estimateur suppose que la similarité des espèces non observées avec toutes les autres est la similarité moyenne observée. 
L'estimation utilise la technique de \textcite{Zhang2014}, qui consiste à développer l'estimateur en série entière au voisinage de $p_s=1$. 
L'estimateur de $\xq{D}{q}{\matrixsym{Z}}{}{}$ est, pour $q\ne 1$,

\begin{equation}
  \xq{\tilde{D}}{q}{\matrixsym{Z}}{}{}
  = {\left\{\hat{K}+\hat{V}
    -\sum_{s\le \xq[\,]{s}{}{}{\ne 0}{}}{\hat{C}\hat{p}_s{\left[\bar{z}\left(1-\hat{C}\hat{p}_s\right)+\hat{C}\hat{p}_s\right]}^{q-1}}\right\}}
      ^{\frac{1}{1-q}}
\end{equation}
  
où

\begin{equation}
  \hat{K}=\sum_{s\le \xq[\,]{s}{}{}{\ne 0}{}}{\hat{C}\hat{p}_s{\left[\left(\sum_{t\le \xq[\,]{s}{}{}{\ne 0}{}}{\hat{C}\hat{p}_t z_{s,t}}\right)+\left(1-\hat{C}\right)\bar{z}\right]}^{q-1}}
\end{equation}

et

\begin{equation}
  \hat{V}=1+\sum_{s\le \xq[\,]{s}{}{}{\ne 0}{}}{\frac{n_s}{n}\sum^{n-n_s}_{v=1}{{\left(1-\bar{z}\right)}^v\left[\prod^v_{i=1}{\frac{i-q}{i}}\right]\left[\prod^v_{j=1}{\left(1-\frac{n_s-1}{n-j}\right)}\right]}}.
\end{equation}

L'estimateur de $\xq{H}{q}{\matrixsym{Z}}{}{}$ est

\begin{equation}
  \xq{\tilde{H}}{q}{\matrixsym{Z}}{}{}
  = \frac{\hat{K}+\hat{V}-\sum_{s\le \xq[\,]{s}{}{}{\ne 0}{}}{\hat{C}\hat{p}_s{\left[\bar{z}\left(1-\hat{C}\hat{p}_s\right)+\hat{C}\hat{p}_s\right]}^{q-1}}-1}{1-q}.
\end{equation}
 
Pour $q=1$,

\begin{equation}
  \xq{\tilde{H}}{1}{\matrixsym{Z}}{}{}
  = \hat{L}+\hat{W}+\sum_{s\le \xq[\,]{s}{}{}{\ne 0}{}}{\hat{C}\hat{p}_s\ln\left[\bar{z}\left(1-\hat{C}\hat{p}_s\right)+\hat{C}\hat{p}_s\right]},
\end{equation}
\begin{equation}
  \xq{\tilde{D}}{1}{\matrixsym{Z}}{}{}=e^{\xq{\tilde{H}}{1}{\matrixsym{Z}}{}{}},
\end{equation}

où

\begin{equation}
  \hat{L}=-\sum_{s\le \xq[\,]{s}{}{}{\ne 0}{}}{\hat{C}\hat{p}_s \ln\left[\left(\sum_{t\le \xq[\,]{s}{}{}{\ne 0}{}}{{\hat{C}\hat{p}}_jz_{s,t}}\right)+\left(1-\hat{C}\right)\bar{z}\right]},
\end{equation}
\begin{equation}
  \hat{W}=\sum_{s\le \xq[\,]{s}{}{}{\ne 0}{}}{\frac{n_s}{n}\sum^{n-n_s}_{v=1}{\frac{{\left(1-\bar{z}\right)}^v}{v}\left[\prod^v_{j=1}{\left(1-\frac{n_s-1}{n-j}\right)}\right]}}.
\end{equation}

Le package \emph{entropart} fournit les fonctions \code{Dqz} et \code{HqZ} pour calculer ces estimateurs.

<<bcDqz>>=
data(Paracou618)
# Matrice de distances fonctionnelles
DistanceMatrix <- as.matrix(Paracou618.dist)
# Matrice de similarité
Z <- 1 - DistanceMatrix/max(DistanceMatrix)
# Calcul de la diversité
Dqz(Paracou618.MC$Ns, q=1, Z)
@


\section{Diversité phylogénétique}

\figureMargin{ArbreA6}
{Arbre phylogénétique ou fonctionnel hypothétique. 
  Rappel de la figure \ref{Arbre}(a).
  5 espèces sont présentes ($S=5$), leurs probabilités notées $p_1$ à $p_5$.
  Les noms des branches sont affichés.
}
{\includegraphics[width=\maxwidth]{ArbreA}}

La diversité phylogénétique $\xq{\bar{D}}{q}{}{}{}(T)$ appliquée à un arbre ultramétrique est un cas particulier de $\xq{D}{q}{\matrixsym{Z}}{}{}$ pour une matrice $\matrixsym{Z}$ dont les lignes et colonnes sont la similarité des \og espèces historiques\fg{}, c'est-à-dire les couples (espèce actuelle; branche ancestrale)\autocite[][proposition A7]{Leinster2012}.

\figureFW{MatricePhylo}
{
  Matrice de similarité correspondant à l'arbre phylogénétique de la figure~\ref{ArbreA6}.
  Les noms des lignes et colonnes sont les couples (espèce actuelle; branche ancestrale).
}
{\footnotesize
\[
 \begin{blockarray}{ccccccccccc}
  (1;b_{1,1})&(1;b_{3,1})&(2;b_{1,2})&(2;b_{3,1})&(3;b_{1,3})&(3;b_{2,3})&(4;b_{1,4})&(4;b_{2,3})&(5;b_{1,5})&(5;b_{2,3}) \\
  \begin{block}{(cccccccccc)c}
       1     &     1     &     0     &     0     &     0     &     0     &     0     &     0     &     0     &     0 & (1;b_{1,1}) \\
       1     &     1     &     1     &     1     &     0     &     0     &     0     &     0     &     0     &     0 & (1;b_{3,1}) \\
       0     &     0     &     1     &     1     &     0     &     0     &     0     &     0     &     0     &     0 & (2;b_{1,2}) \\
       1     &     1     &     1     &     1     &     0     &     0     &     0     &     0     &     0     &     0 & (2;b_{3,1}) \\
       0     &     0     &     0     &     0     &     1     &     1     &     0     &     0     &     0     &     0 & (3;b_{1,3}) \\
       0     &     0     &     0     &     0     &     1     &     1     &     1     &     1     &     1     &     1 & (3;b_{2,3}) \\
       0     &     0     &     0     &     0     &     0     &     0     &     1     &     1     &     0     &     0 & (4;b_{1,4}) \\
       0     &     0     &     0     &     0     &     1     &     1     &     1     &     1     &     1     &     1 & (4;b_{2,3}) \\
       0     &     0     &     0     &     0     &     0     &     0     &     0     &     0     &     1     &     1 & (5;b_{1,5}) \\
       0     &     0     &     0     &     0     &     1     &     1     &     1     &     1     &     1     &     1 & (5;b_{2,3}) \\
  \end{block}
 \end{blockarray}
\]
}

Par exemple, Figure~\ref{ArbreA6}: l'espèce 1 et les branches $b_{1,1}$ et $b_{3,1}$ fournissent les deux premières lignes et colonnes de la matrice; l'espèce 5 et les branches $b_{1,5}$ et $b_{2,3}$, les deux dernières.  

La diversité phylogénétique $\xq{\hat{D}}{q}{}{}{}(T)$ est obtenue quand les éléments de la matrice $\matrixsym{Z}$, en figure~\ref{MatricePhylo}, suivent les règles suivantes: les éléments de toutes les colonnes correspondant à une espèce donnée (par exemple les deux premières colonnes qui correspondent à l'espèce 1) valent 1 pour toutes les lignes correspondant à une branche dont l'espèce descend (les trois lignes correspondant aux branches $b_{1,1}$ et $b_{3,1}$); les éléments dont l'espèce en colonne ne descend pas de la branche en ligne valent 0. 
La matrice n'est donc pas symétrique, mais c'est une matrice de similarité dont la diagonale vaut 1.

La probabilité de chaque espèce historique est la somme de celles des espèces actuelles qui en descendent, multipliée par la longueur de la branche normalisée par la hauteur de l'arbre.
Dans l'exemple, la hauteur totale de l'arbre est $T=T_1 + T_2 + T_3$.
Les probabilités des espèces historiques sont
$$(p_1 \frac{l(b_{1,1})}{T}, (p_1 + p_2) \frac{l(b_{3,1})}{T}, p_2 \frac{l(b_{1,2})}{T}, \dots, (p_3 + p_4 + p_5) \frac{l(b_{3,1})}{T}).$$

Les dimensions de la matrice de similarité et du vecteur de probabilités devient rapidement très grande et leur écriture pénible: il est bien plus simple de calculer la diversité phylogénétique à partir des distances dans l'arbre et des probabilités des espèces.
Cette équivalence de méthodes n'a donc pas d'intérêt pratique mais montre que la diversité de Leinster et Cobbold généralise la diversité phylogénétique.
Cependant, le calcul de $\xq{\hat{D}}{q}{\matrixsym{Z}}{}{}$ à partir d'une matrice $\matrixsym{Z}$ qui serait la simple transformation des distances de l'arbre phylogénétique, c'est-à-dire 1 moins les distances normalisées par la hauteur de l'arbre, ne donne pas la valeur de la diversité phylogénétique $\xq{\bar{D}}{q}{}{}{}(T)$, sauf dans le cas particulier de la diversité de Rao, $q=2$.

Pour un arbre non ultramétrique, il est possible de définir une matrice $\matrixsym{Z}$ similaire à celle de la figure~\ref{MatricePhylo}, mais ses valeurs non nulles ne sont pas égales à 1.
Elles sont égales au rapport de $\bar{T}$, la longueur moyenne des branches pondérée par la fréquence des espèces, sur la longueur de la branche: elles dépendent donc des fréquences des espèces et empêchent par conséquent la comparaison de la diversité entre communautés différentes.


\section{Diversité individuelle}

La diversité $\xq{D}{q}{\matrixsym{Z}}{}{}$ et tous ses cas particuliers (phylodiversité et diversité neutre) peuvent être envisagés au niveau individuel plutôt qu'au niveau de l'espèce.

Le calcul de la diversité n'est pas affecté par le remplacement d'une espèce par deux espèces identiques.
La ligne et la colonne de la matrice $\matrixsym{Z}$, correspondant à l'espèce $s$ sont remplacées par deux lignes et colonnes identiques correspondant aux espèces $s'$ et $s''$, dont la similarité avec les autres espèces est la même que celle de l'espèce $s$ et la similarité entre elles égale à 1, les probabilités vérifiant $p_s=p_{s'}+p_{s''}$. 
L'opération peut être répétée jusqu'à la désagrégation complète de la matrice où chaque ligne correspondrait à un individu et les probabilités seraient égales à $\nicefrac{1}{N}$. 
Il n'y donc pas de différence entre la mesure de la diversité individuelle et celle de la diversité spécifique qui n'est qu'une façon pratique de regrouper des individus ayant la même banalité. 
Dit autrement, l'entropie d'une communauté est la somme des entropie de ses espèces, qui n'est que la somme pondérée des entropies individuelles si tous les individus d'une espèce ont la même entropie.

La variabilité intraspécifique peut être traitée par un raisonnement similaire.
L'idée d'intégrer aux mesures de diversité la possibilité que tous les individus d'une espèce ne soient pas semblables émerge dans la littérature\autocite{Pavoine2014b, Chiu2014b}.
Mais si des individus de la même espèce ne sont pas totalement similaires, ils ne peuvent pas être regroupés en prenant pour similarité de l'espèce avec elle-même une valeur unique qui résumerait la similarité entre les individus (au lieu de 1) pour tous les ordres de diversité.

Formellement, si l'espèce $s$ est composée de deux groupes $s'$ et $s''$, la banalité du groupe $s'$ est
$${\left(\vectorsym{Zp}\right)}_{s'}=\sum_{t \ne s', s''}{p_{t}z_{s',t}} + p_{s'} + p_{s''}z_{s',s''},$$
celle du groupe $s''$ est
$${\left(\vectorsym{Zp}\right)}_{s''}=\sum_{t \ne s', s''}{p_{t}z_{s'',t}} + p_{s'}z_{s',s''} + p_{s''}.$$
Les similarités avec les autres espèces sont identiques : $z_{s,t}=z_{s',t}=z_{s'',t}$. 
La contribution à la diversité des deux groupes
$$\sum_{s'}{p_{s'}{\left(\vectorsym{Zp}\right)}^{q-1}_{s'}}+\sum_{s''}{p_{s''}{\left(\vectorsym{Zp}\right)}^{q-1}_{s''}}$$
est remplacée après regroupement par
$$\sum_{s}{p_{s}{\left(\vectorsym{Zp}\right)}^{q-1}_{s}}.$$
Puisque $p_s=p_{s'}+p_{s''}$, le regroupement n'est possible quel que soit $q$ que si les banalités des deux groupes sont identiques, ce qui interdit toute variabilité intraspécifique: $z_{s',s''}$ est obligatoirement égal à 1. 
La non-linéarité de la moyenne généralisée ne permet pas de définir une matrice de similarité intégrant la variabilité intraspécifique.

Dans le cas de la diversité de Rao ($q=2$), on peut chercher la valeur de $z_{s,s}$, différente de 1, définissant la similarité de l'espèce avec elle même pour prendre en compte sa variabilité. La résolution de l'équation
$$\sum_{s'}{p_{s'}{\left(\vectorsym{Zp}\right)}_{s'}}+\sum_{s''}{p_{s''}{\left(\vectorsym{Zp}\right)}_{s''}} = \sum_{s}{p_{s}{\left(\vectorsym{Zp}\right)}_{s}}$$
permet de trouver
$$z_{s,s}=1+ \nicefrac{2 p_{s'} p_{s''}(z_{s',s''}-1)}{p_s^2}.$$
Dans le cas le plus simple où $p_{s'}=p_{s''}$, la similarité intraspécifique est $\nicefrac{(1+z_{s',s''})}{2}$. 
La valeur de $z_{s,s}$ peut être cherchée pour n'importe quelle valeur de $q$, mais la résolution de l'équation est en général impossible analytiquement, et $z_{s,s}$ varie avec $q$.
Se limiter à $q=2$ simplifie le problème.

L'exemple suivant considère deux espèces, dont une comprenant deux groupes:
<<VarIntraspecifique>>=
# Similarité entre les deux groupes
zs12 <- .9
# Probabilités des deux groupes
ps1 <- 1/5
ps2 <- 1/5
# Matrice de similarité
(Z2s <- matrix(c(1,zs12,.5, zs12,1,.5, .5,.5,1), nrow = 3))
# Probabilités
(P2s <- c(ps1, ps2, 1-ps1-ps2))
# Diversité
Dqz(P2s, 2, Z2s)

# Similarité intraspécifique après regroupement
(zss <- 1+2*ps1*ps2/(ps1+ps2)^2*(zs12-1))
# Matrice de similarité après regroupement
(Z1s <- matrix(c(zss,.5, .5,1), nrow = 2))
# Probabilité après regroupement
(P1s <- c(ps1+ps2, 1-ps1-ps2))
# Diversité
Dqz(P1s, 2, Z1s)
@


En pratique, si les similarités entre individus ou groupes sont connues, le regroupement n'a aucun intérêt. 
Mais en absence de données individuelles, il est possible de choisir arbitrairement une similarité intraspécifique différente de 1 (ou de façon équivalente une distance différente de 0) pour calculer une diversité d'ordre fixé, de préférence 2.


\section{Diversité des valeurs propres}

L'approche de \textcite{Pavoine2014} permet de prendre en compte la variabilité intraspécifique de façon rigoureuse.
Pour mesurer la diversité neutre, les espèces sont placées dans un espace multidimensionnel, de dimension $S$. Chaque espèce est représentée par un vecteur de longueur $p_s$ sur son axe. Cette représentation a été utilisée par \textcite{Campos2009} qui ont relié la diversité de Simpson au volume de la sphère sur laquelle se trouve le point définissant la communauté (Figure~\ref{Campos2009}).

\figureSC{Campos2009}
{Représentation d'une communauté dans un espace multidimensionnel dont chaque axe correspond à une espèce.
  La communauté est composée de trois espèces.
  Le point représentant la communauté se trouve sur la sphère de rayon $r=\sqrt{\sum_s{p_s^2}}$.
  Le plan (qui est en réalité un hyperplan de dimension $S-1$) d'équation $\sum_s{p_s}=1$ est représenté par un triangle.
  (\emph{in} Campos et Isaza, 2009)}
{\includegraphics[width=.8\maxwidth]{Campos2009}}

La matrice de similarité entre les espèces $\matrixsym{Z}$ permet d'affiner la représentation. Soit la matrice $\matrixsym{C}=\sqrt{\matrixsym{Z}}$.
Chaque espèce $s$ est maintenant représentée par le vecteur dont la coordonnée sur l'axe $t$ est $\sqrt{p_s p_t}c_{s,t}$. 
Les axes correspondent aux espèces \og pures\fg{}, totalement dissimilaires, les vecteurs des espèces réelles prennent en compte la similarité. 
Dans le cas extrême de la diversité neutre, $\matrixsym{C}=\matrixsym{I}$, chaque espèce est située uniquement sur son axe. 
Dans l'autre cas extrême de totale similarité, où $\matrixsym{C}$ ne contient que des 1, toutes les espèces sont colinéaires.

Il est possible de calculer les $S$ valeurs propres notées $\lambda_s$ de la matrice des coordonnées des espèces et de les normaliser : $\mu_s=\nicefrac{\lambda_s}{\sum_s{\lambda_s}}$.
La communauté peut maintenant être représentée par ses valeurs propres $\mu_s$ correspondant à la proportion d'une \og espèce composite\fg{} pure sur chaque axe généré par les vecteurs propres: cette transformation est une ACP non centrée, non réduite.
La diversité HCDT des valeurs propres est la diversité de la communauté, qui sera notée ici $\xq{D}{q}{\matrixsym{Z}}{}{}(\Lambda)$.

La définition de cette diversité autorise toute matrice $\matrixsym{C}$ symétrique, dont les valeurs de similarité sont positives ou nulles, strictement positives sur la diagonale.
Si $\matrixsym{C}$ est la racine carrée d'une matrice de similarité au sens strict $\matrixsym{Z}$, c'est-à-dire contenant des valeurs comprises entre 0 et 1 et dont les éléments de la diagonale sont tous égaux à 1, alors $\xq{D}{2}{\matrixsym{Z}}{}{}(\Lambda)$ est égale à la diversité de Rao appliquée à une matrice de distances $\matrixsym{D}=1-\matrixsym{Z}$.
La définition de $\matrixsym{C}$ comme racine carrée de $\matrixsym{Z}$ se justifie par des raisons géométriques: la norme de chaque vecteur représentant une espèce est la racine carrée de la somme des carrés de ses coordonnées.
Le carré de la norme du vecteur de l'espèce $s$ est donc $p_s$ multiplié par la banalité de l'espèce.

Si $\matrixsym{Z}=\matrixsym{I}_s$, l'ACP ne modifie pas le nuage de points original et $\xq{D}{q}{\matrixsym{Z}}{}{}(\Lambda)=\xq{D}{q}{}{}{}$.

L'exemple suivant calcule la diversité de la méta-communauté \code{Paracou618} selon la matrice de distances \code{Paracou618.dist}.
<<DqZLambda>>=
# Probabilités
Ps <- Paracou618.MC$Ps[Paracou618.MC$Ps>0]
# Matrice de distances fonctionnelles
DistanceMatrix <- as.matrix(Paracou618.dist)
# Transformation en matrice de similarité
Z <- 1 - DistanceMatrix/max(DistanceMatrix)
# Mise en correspondance de la matrice et du vecteur de probabilités
Z <- Z[names(Ps), names(Ps)]
# Matrice diagonale contenant les probabilités
Q <- diag(Ps)
# Matrice des espèces (les lignes de Sp sont les coordonnées des vecteurs)
Sp <- sqrt(Q %*% Z %*% Q)
# Valeurs propres normalisées
Lambda <- svd(Sp)$d
Mu <- Lambda/sum(Lambda)
# Comparaison des valeurs à q=2
Diversity(Mu, 2)
Dqz(Ps, 2, Z)
# La valeur à q=0 est le nombre d'espèces
Diversity(Mu, 0)
length(Ps)
@

La valeur de la diversité des valeurs propres est légèrement différente de celle de la diversité de Leinster et Cobbold à cause des approximations numériques liées au calcul des valeurs propres (qui nécessitent l'inversion d'une matrice carrée de dimension $S$).

Le profil de diversité se trouve en Figure~\ref{DqZLambdaFig}
\verbfootnote{
  Code R:
  <<DqZLambdaCode, eval=FALSE>>=
  DqZLambda<- CommunityProfile(Diversity, Mu)
  Xlab <- "Ordre de diversité"
  Ylab <- "Diversité"
  plot(DqZLambda, log="y", xlab=Xlab, ylab=Ylab)
  @
}.

\figureSC{DqZLambdaFig}
{Profil de diversité des valeurs propres de la méta-communauté \code{Paracou618}.}
{
  <<DqZLambdaFig, echo=FALSE, results='hide'>>=
  <<DqZLambdaCode>>
  @
}

La diversité des valeurs propres permet de ramener le problème de la diversité d'espèces partiellement similaires au calcul de la diversité neutre d'une communauté d'espèces composites totalement dissimilaires.

Les éléments de la diagonale de la matrice de similarité ne sont pas forcément égaux à 1: des valeurs inférieures correspondent à la variabilité intraspécifique, selon le mécanisme de regroupement traité au paragraphe précédent.
Les raisons qui empêchent d'utiliser des valeurs de similarité intraspécifique différentes de 1 dans le calcul de la diversité de Leinster et Cobbold ne s'appliquent pas ici : quelle que soit la valeur de $q$, les valeurs propres sont les mêmes.

Les limites de la diversité des valeurs propres sont cependant nombreuses. La première est numérique: son calcul est imprécis dans des communautés très riches. L'inversion d'une matrice de dimension 200 ou plus est toujours problématique. 

Les espèces non échantillonnées entraînent un biais d'estimation: le nombre de dimensions est sous-estimé. Comme les espèces manquantes ont une faible probabilité, leur vecteur est petit et n'influe pas beaucoup sur la diagonalisation de la matrice.
Les valeurs propres manquantes sont donc petites.
Elles influent sur la diversité pour les faibles valeurs de $q$, notamment la diversité d'ordre 0 qui est le nombre de dimensions de la matrice des espèces (en général, le nombre d'espèces, ou une valeur inférieure si des espèces sont colinéaires). 
Il n'existe pas de technique pour corriger ce biais d'estimation.

La composition de la communauté en espèces composites dépend à la fois de la matrice de similarité et des probabilités des espèces réelles. 
Elle est donc unique pour chaque communauté, ce qui empêche toute décomposition de la diversité selon les méthodes présentées plus loin.



\section{Synthèse}

$\xq{D}{q}{}{}{}(T)$ est l'exponentielle d'ordre $q$ de la moyenne pondérée de l'entropie HCDT calculée à chaque période de l'arbre phylogénétique.

$\xq{D}{q}{\matrixsym{Z}}{}{}$ est l'exponentielle d'ordre $q$ de l'entropie de Ricotta et Szeidl, mais aussi l'inverse de la banalité moyenne des espèces de la communauté.

$\xq{D}{q}{\matrixsym{Z}}{}{}$ et $\xq{D}{q}{}{}{}$ sont des nombres effectifs d'espèces, respectent toutes les propriétés demandées à une mesure de diversité dont le principe de réplication. 
Leurs valeurs sont identiques pour $q=2$ (diversité de Rao). 
$\xq{D}{q}{\matrixsym{Z}}{}{}$ est moins sensible au paramètre $q$ que $\xq{D}{q}{}{}{}(T)$: la Figure~\ref{ComparaisonDqFig}
\verbfootnote{Le code R nécessaire pour réaliser la figure est:
  <<ComparaisonDqCode, eval=FALSE>>=
  q <- c(seq(0, 3, 0.1))
  DistanceMatrix <- as.matrix(Paracou618.Taxonomy$Wdist^2/2)
  Z <- 1 - DistanceMatrix/max(DistanceMatrix)
  Divqz <- sapply(q, function(q) Dqz(Paracou618.MC$Ps, q, Z))
  Divq <- sapply(q,
       function(q) ChaoPD(Paracou618.MC$Ps, q=q, PhyloTree=Paracou618.Taxonomy))
  plot(y=Divq, x=q, type="l", ylab="Diversity", lty=2)
  lines(y=Divqz, x=q, lty=1)
  @
} compare les deux mesures.
Le rôle du paramètre est assez différent: dans $\xq{D}{q}{\matrixsym{Z}}{}{}$, la banalité des espèces est à la puissance $q$ alors que leur probabilité est à la puissance 1.
Le paramètre détermine l'importance donnée aux espèces \emph{originales}, c'est-à-dire dont la banalité est petite, et non aux espèces \emph{rares}.
Les deux notions se confondent quand la diversité neutre est considérée: la banalité d'une espèce se réduit alors à sa fréquence.

\figureSC{ComparaisonDqFig}
  {Diversité phylogénétique (l'arbre est une taxonomie) d'ordre $q$ de deux hectares de forêt de Paracou: $\xq{D}{q}{\matrixsym{Z}}{}{}$ (trait plein) et $\xq{\hat{D}}{q}{}{}{}(T)$ (pointillé).}
  {
<<ComparaisonDqFig, echo=FALSE, results='hide'>>=
<<ComparaisonDqCode>>
@
}

$\xq{D}{q}{\matrixsym{Z}}{}{}$ est particulièrement intéressante pour mesurer la diversité fonctionnelle, souvent définie à partir d'une matrice de distances entre les espèces. 
La transformation d'une matrice en un arbre phylogénétique déforme les données \autocite{Pavoine2005a, Podani2006, Podani2007}. 
La diversité de Leinster et Cobbold est calculée directement à partir de la matrice.

Si l'arbre phylogénétique n'est pas ultramétrique, le calcul de la diversité est possible, mais la matrice $\matrixsym{Z}$ contient alors des valeurs comprises entre 0 et 1 qui dépendent des effectifs des espèces actuelles (ils interviennent dans le calcul de la hauteur de l'arbre qui est la moyenne de la longueur des branches). 
La dépendance entre similarité et fréquence des espèces constitue un problème théorique qui empêche d'interpréter la diversité calculée à partir d'un arbre non ultramétrique.

Enfin, il est possible de désagréger les données jusqu'au niveau individuel si la distance entre paires d'individus est connue.
En revanche, la prise en compte de la variabilité intraspécifique par une similarité intraspécifique inférieure à 1 n'est possible que pour un ordre de diversité fixé: il n'est pas possible d'obtenir un profil de diversité de cette façon.
